use serde_json::json;
use std::collections::HashSet;

use super::{ManifestMethod, RenderedManifest};

/// Configuration for manifest generation
pub struct ManifestConfig<'a> {
    pub contract_name: &'a str,
    pub author: &'a str,
    pub description: &'a str,
    pub version: &'a str,
    pub email: Option<&'a str>,
}

impl<'a> Default for ManifestConfig<'a> {
    fn default() -> Self {
        Self {
            contract_name: "",
            author: "R3E Network",
            description: "Generated by wasm-neovm translator",
            version: "1.0.0",
            email: None,
        }
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    build_manifest_with_config(
        ManifestConfig {
            contract_name,
            ..Default::default()
        },
        methods,
    )
}

pub fn build_manifest_with_config(
    config: ManifestConfig,
    methods: &[ManifestMethod],
) -> RenderedManifest {
    let supported_standards = detect_supported_standards(methods);
    let extra = if let Some(email) = config.email {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
            "email": email,
        })
    } else {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
        })
    };

    let manifest = json!({
        "name": config.contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": supported_standards,
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": extra,
    });

    // Neo manifest compatibility: omit explicit false feature flags.
    if let Some(features) = manifest
        .get("features")
        .and_then(serde_json::Value::as_object)
    {
        let all_false_or_empty = features
            .values()
            .all(|value| value.as_bool().map(|b| !b).unwrap_or(false));
        if all_false_or_empty {
            // Safe to mutate because we just created this object literal.
            let mut manifest = manifest;
            manifest["features"] = json!({});
            return RenderedManifest { value: manifest };
        }
    }

    RenderedManifest { value: manifest }
}

fn detect_supported_standards(methods: &[ManifestMethod]) -> Vec<String> {
    let names: HashSet<String> = methods
        .iter()
        .map(|method| normalize_method_name(&method.name))
        .collect();

    let mut standards = Vec::new();

    // NEP-17 (fungible): symbol, decimals, totalSupply, balanceOf, transfer and no ownerOf.
    let nep17_required = ["symbol", "decimals", "totalsupply", "balanceof", "transfer"];
    let has_ownerof = names.contains("ownerof");
    if nep17_required.iter().all(|name| names.contains(*name)) && !has_ownerof {
        standards.push("NEP-17".to_string());
    }

    // NEP-11 (NFT): balanceOf + ownerOf + transfer mechanism.
    let has_nep11_transfer =
        names.contains("transfer") || names.contains("transferfrom") || names.contains("tokensof");
    if names.contains("balanceof") && has_ownerof && has_nep11_transfer {
        standards.push("NEP-11".to_string());
    }

    // NEP-24 (royalty/discovery): tokenURI or royaltyInfo.
    if names.contains("tokenuri") || names.contains("royaltyinfo") {
        standards.push("NEP-24".to_string());
    }

    // NEP-22: update(nefFile, manifest, data).
    if has_method_arity(methods, "update", 3) {
        standards.push("NEP-22".to_string());
    }

    // NEP-26: onNEP11Payment(from, amount, tokenId, data).
    if has_method_arity(methods, "onNEP11Payment", 4) {
        standards.push("NEP-26".to_string());
    }

    // NEP-27: onNEP17Payment(from, amount, data).
    if has_method_arity(methods, "onNEP17Payment", 3) {
        standards.push("NEP-27".to_string());
    }

    // NEP-29: _deploy(data, update).
    if methods
        .iter()
        .any(|method| method.name.eq_ignore_ascii_case("_deploy") && method.parameters.len() == 2)
    {
        standards.push("NEP-29".to_string());
    }

    // NEP-30: verify(...) returning Boolean.
    let verify_methods: Vec<&ManifestMethod> = methods
        .iter()
        .filter(|method| normalize_method_name(&method.name) == "verify")
        .collect();
    if verify_methods.len() == 1
        && (verify_methods[0]
            .return_type
            .eq_ignore_ascii_case("Boolean")
            || verify_methods[0].return_type.eq_ignore_ascii_case("Bool"))
    {
        standards.push("NEP-30".to_string());
    }

    // NEP-31: destroy() with void return.
    if methods.iter().any(|method| {
        normalize_method_name(&method.name) == "destroy"
            && method.parameters.is_empty()
            && method.return_type.eq_ignore_ascii_case("Void")
    }) {
        standards.push("NEP-31".to_string());
    }

    standards
}

fn has_method_arity(methods: &[ManifestMethod], method_name: &str, arity: usize) -> bool {
    let normalized = normalize_method_name(method_name);
    methods.iter().any(|method| {
        normalize_method_name(&method.name) == normalized && method.parameters.len() == arity
    })
}

fn normalize_method_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c != '_' && c != '-' {
            out.push(c.to_ascii_lowercase());
        }
    }
    out
}
