use serde_json::json;
use std::collections::HashSet;

use super::{ManifestMethod, RenderedManifest};

/// Configuration for manifest generation
pub struct ManifestConfig<'a> {
    pub contract_name: &'a str,
    pub author: &'a str,
    pub description: &'a str,
    pub version: &'a str,
    pub email: Option<&'a str>,
}

impl<'a> Default for ManifestConfig<'a> {
    fn default() -> Self {
        Self {
            contract_name: "",
            author: "R3E Network",
            description: "Generated by wasm-neovm translator",
            version: "1.0.0",
            email: None,
        }
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    build_manifest_with_config(
        ManifestConfig {
            contract_name,
            ..Default::default()
        },
        methods,
    )
}

pub fn build_manifest_with_config(
    config: ManifestConfig,
    methods: &[ManifestMethod],
) -> RenderedManifest {
    let supported_standards = detect_supported_standards(methods);
    let extra = if let Some(email) = config.email {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
            "email": email,
        })
    } else {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
        })
    };

    let manifest = json!({
        "name": config.contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": supported_standards,
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": extra,
    });

    // Neo manifest compatibility: omit explicit false feature flags.
    if let Some(features) = manifest
        .get("features")
        .and_then(serde_json::Value::as_object)
    {
        let all_false_or_empty = features
            .values()
            .all(|value| value.as_bool().map(|b| !b).unwrap_or(false));
        if all_false_or_empty {
            // Safe to mutate because we just created this object literal.
            let mut manifest = manifest;
            manifest["features"] = json!({});
            return RenderedManifest { value: manifest };
        }
    }

    RenderedManifest { value: manifest }
}

fn detect_supported_standards(methods: &[ManifestMethod]) -> Vec<String> {
    struct MethodSignatureRule {
        standard: &'static str,
        method_name: &'static str,
        return_type: &'static str,
        expected_kinds: &'static [&'static [&'static str]],
    }

    const UPDATE_PARAM_0: &[&str] = &["ByteString", "ByteArray", "Buffer", "Any"];
    const UPDATE_PARAM_1: &[&str] = &["String", "Str", "Any"];
    const HASH160_COMPAT: &[&str] = &["Hash160", "UInt160", "ScriptHash", "ByteString", "Any"];
    const INTEGER_COMPAT: &[&str] = &["Integer", "Int", "Any"];
    const TOKEN_ID_COMPAT: &[&str] = &["ByteString", "ByteArray", "Buffer", "Any"];
    const DEPLOY_FLAG_COMPAT: &[&str] = &["Boolean", "Bool", "Any"];
    const ANY_PARAM: &[&str] = &[];

    const LIFECYCLE_RULES: &[MethodSignatureRule] = &[
        MethodSignatureRule {
            standard: "NEP-22",
            method_name: "update",
            return_type: "Void",
            expected_kinds: &[UPDATE_PARAM_0, UPDATE_PARAM_1, ANY_PARAM],
        },
        MethodSignatureRule {
            standard: "NEP-26",
            method_name: "onNEP11Payment",
            return_type: "Void",
            expected_kinds: &[HASH160_COMPAT, INTEGER_COMPAT, TOKEN_ID_COMPAT, ANY_PARAM],
        },
        MethodSignatureRule {
            standard: "NEP-27",
            method_name: "onNEP17Payment",
            return_type: "Void",
            expected_kinds: &[HASH160_COMPAT, INTEGER_COMPAT, ANY_PARAM],
        },
        MethodSignatureRule {
            standard: "NEP-29",
            method_name: "_deploy",
            return_type: "Void",
            expected_kinds: &[ANY_PARAM, DEPLOY_FLAG_COMPAT],
        },
    ];

    let names: HashSet<String> = methods
        .iter()
        .map(|method| normalize_method_name(&method.name))
        .collect();

    let mut standards = Vec::new();

    // NEP-17 (fungible): symbol, decimals, totalSupply, balanceOf, transfer and no ownerOf.
    let has_ownerof = names.contains("ownerof");
    let has_nep17_shape =
        has_method_with_arity_and_return(methods, "symbol", 0, &["String", "Any"])
            && has_method_with_arity_and_return(methods, "decimals", 0, &["Integer", "Any"])
            && has_method_with_arity_and_return(methods, "totalsupply", 0, &["Integer", "Any"])
            && has_method_with_arity_and_return(methods, "balanceof", 1, &["Integer", "Any"])
            && has_method_with_arities_and_return(
                methods,
                "transfer",
                &[3, 4],
                &["Boolean", "Bool", "Any"],
            );
    if has_nep17_shape && !has_ownerof {
        standards.push("NEP-17".to_string());
    }

    // NEP-11 (NFT): balanceOf + ownerOf + transfer mechanism.
    let has_nep11_transfer = has_method_with_arities_and_return(
        methods,
        "transfer",
        &[3, 4],
        &["Boolean", "Bool", "Any"],
    ) || has_method_with_arities(methods, "transferfrom", &[3, 4, 5])
        || has_method_with_arities(methods, "tokensof", &[1]);
    let has_nep11_shape =
        has_method_with_arity_and_return(methods, "balanceof", 1, &["Integer", "Any"])
            && has_method_with_arity(methods, "ownerof", 1);
    if has_nep11_shape && has_nep11_transfer {
        standards.push("NEP-11".to_string());
    }

    // NEP-24 (royalty/discovery): tokenURI or royaltyInfo.
    if names.contains("tokenuri") || names.contains("royaltyinfo") {
        standards.push("NEP-24".to_string());
    }

    for rule in LIFECYCLE_RULES {
        if has_method_signature_with_kinds(
            methods,
            rule.method_name,
            rule.return_type,
            rule.expected_kinds,
        ) {
            standards.push(rule.standard.to_string());
        }
    }

    // NEP-30: verify(...) returning Boolean.
    let verify_methods: Vec<&ManifestMethod> = methods
        .iter()
        .filter(|method| normalize_method_name(&method.name) == "verify")
        .collect();
    if verify_methods.len() == 1
        && (verify_methods[0]
            .return_type
            .eq_ignore_ascii_case("Boolean")
            || verify_methods[0].return_type.eq_ignore_ascii_case("Bool"))
    {
        standards.push("NEP-30".to_string());
    }

    // NEP-31: destroy() with void return.
    if methods.iter().any(|method| {
        normalize_method_name(&method.name) == "destroy"
            && method.parameters.is_empty()
            && method.return_type.eq_ignore_ascii_case("Void")
    }) {
        standards.push("NEP-31".to_string());
    }

    standards
}

fn has_method_signature_with_kinds(
    methods: &[ManifestMethod],
    method_name: &str,
    return_type: &str,
    expected_kinds: &[&[&str]],
) -> bool {
    let normalized = normalize_method_name(method_name);
    methods.iter().any(|method| {
        normalize_method_name(&method.name) == normalized
            && method.parameters.len() == expected_kinds.len()
            && method.return_type.eq_ignore_ascii_case(return_type)
            && method_matches_param_kinds(method, expected_kinds)
    })
}

fn has_method_with_arity(methods: &[ManifestMethod], method_name: &str, arity: usize) -> bool {
    let normalized = normalize_method_name(method_name);
    methods.iter().any(|method| {
        normalize_method_name(&method.name) == normalized && method.parameters.len() == arity
    })
}

fn has_method_with_arities(
    methods: &[ManifestMethod],
    method_name: &str,
    arities: &[usize],
) -> bool {
    arities
        .iter()
        .any(|arity| has_method_with_arity(methods, method_name, *arity))
}

fn has_method_with_arity_and_return(
    methods: &[ManifestMethod],
    method_name: &str,
    arity: usize,
    accepted_returns: &[&str],
) -> bool {
    let normalized = normalize_method_name(method_name);
    methods.iter().any(|method| {
        normalize_method_name(&method.name) == normalized
            && method.parameters.len() == arity
            && return_type_matches(&method.return_type, accepted_returns)
    })
}

fn has_method_with_arities_and_return(
    methods: &[ManifestMethod],
    method_name: &str,
    arities: &[usize],
    accepted_returns: &[&str],
) -> bool {
    arities.iter().any(|arity| {
        has_method_with_arity_and_return(methods, method_name, *arity, accepted_returns)
    })
}

fn normalize_method_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c != '_' && c != '-' {
            out.push(c.to_ascii_lowercase());
        }
    }
    out
}

fn normalize_type_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        }
    }
    out
}

fn kind_matches(actual: &str, accepted: &[&str]) -> bool {
    if accepted.is_empty() {
        return true;
    }

    let normalized_actual = canonical_type_name(actual);
    if normalized_actual.is_empty() {
        return false;
    }

    accepted.iter().any(|candidate| {
        let normalized_candidate = canonical_type_name(candidate);
        !normalized_candidate.is_empty() && normalized_actual == normalized_candidate
    })
}

fn canonical_type_name(name: &str) -> String {
    let normalized = normalize_type_name(name);
    match normalized.as_str() {
        "bool" | "boolean" => "boolean".to_string(),
        "int" | "integer" => "integer".to_string(),
        "str" | "string" => "string".to_string(),
        "bytestring" | "bytearray" | "buffer" => "bytestring".to_string(),
        "hash160" | "uint160" | "scripthash" => "hash160".to_string(),
        _ => normalized,
    }
}

fn return_type_matches(actual: &str, accepted: &[&str]) -> bool {
    if accepted.is_empty() {
        return true;
    }
    let normalized_actual = canonical_type_name(actual);
    if normalized_actual.is_empty() {
        return false;
    }
    accepted.iter().any(|candidate| {
        let normalized_candidate = canonical_type_name(candidate);
        !normalized_candidate.is_empty() && normalized_actual == normalized_candidate
    })
}

fn method_matches_param_kinds(method: &ManifestMethod, expected_kinds: &[&[&str]]) -> bool {
    method
        .parameters
        .iter()
        .zip(expected_kinds.iter())
        .all(|(parameter, accepted)| kind_matches(&parameter.kind, accepted))
}
