use serde_json::json;

use super::{ManifestMethod, RenderedManifest};

/// Configuration for manifest generation
pub struct ManifestConfig<'a> {
    pub contract_name: &'a str,
    pub author: &'a str,
    pub description: &'a str,
    pub version: &'a str,
    pub email: Option<&'a str>,
}

impl<'a> Default for ManifestConfig<'a> {
    fn default() -> Self {
        Self {
            contract_name: "",
            author: "R3E Network",
            description: "Generated by wasm-neovm translator",
            version: "1.0.0",
            email: None,
        }
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    build_manifest_with_config(
        ManifestConfig {
            contract_name,
            ..Default::default()
        },
        methods,
    )
}

pub fn build_manifest_with_config(
    config: ManifestConfig,
    methods: &[ManifestMethod],
) -> RenderedManifest {
    let extra = if let Some(email) = config.email {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
            "email": email,
        })
    } else {
        json!({
            "author": config.author,
            "description": config.description,
            "version": config.version,
        })
    };

    let manifest = json!({
        "name": config.contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": [],
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": extra,
    });

    RenderedManifest { value: manifest }
}
