use anyhow::{bail, Result};
use serde::Serialize;
use serde_json::{json, Value};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, Serialize)]
pub struct ManifestParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ManifestMethod {
    pub name: String,
    pub parameters: Vec<ManifestParameter>,
    #[serde(rename = "returntype")]
    pub return_type: String,
    pub offset: u32,
    pub safe: bool,
}

#[derive(Debug, Clone)]
pub struct RenderedManifest {
    pub value: serde_json::Value,
}

impl RenderedManifest {
    pub fn to_string(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(&self.value)
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    let manifest = json!({
        "name": contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": [],
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": {
            "author": "neo-llvm",
            "description": "Generated by wasm-neovm translator",
        }
    });

    RenderedManifest { value: manifest }
}

pub fn merge_manifest(base: &mut serde_json::Value, overlay: &serde_json::Value) {
    if let (Some(base_map), Some(overlay_map)) = (base.as_object_mut(), overlay.as_object()) {
        for (key, value) in overlay_map {
            match base_map.get_mut(key) {
                Some(existing) => merge_manifest(existing, value),
                None => {
                    base_map.insert(key.clone(), value.clone());
                }
            }
        }
        dedup_manifest_collections(base_map);
        return;
    }

    if let (Some(base_arr), Some(overlay_arr)) = (base.as_array_mut(), overlay.as_array()) {
        base_arr.extend(overlay_arr.iter().cloned());
        return;
    }

    *base = overlay.clone();
}

pub fn propagate_safe_flags(manifest: &mut serde_json::Value) {
    let Some(abi) = manifest
        .get_mut("abi")
        .and_then(|value| value.as_object_mut())
    else {
        return;
    };
    let Some(methods) = abi
        .get_mut("methods")
        .and_then(|methods| methods.as_array_mut())
    else {
        return;
    };

    let mut safe_names: HashSet<String> = HashSet::new();
    for method in methods.iter() {
        if method
            .get("safe")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false)
        {
            if let Some(name) = method.get("name").and_then(serde_json::Value::as_str) {
                safe_names.insert(name.to_string());
            }
        }
    }

    if safe_names.is_empty() {
        return;
    }

    for method in methods.iter_mut() {
        if let Some(name) = method.get("name").and_then(serde_json::Value::as_str) {
            if safe_names.contains(name) {
                if let Some(obj) = method.as_object_mut() {
                    obj.insert("safe".to_string(), serde_json::Value::Bool(true));
                }
            }
        }
    }
}

fn dedup_manifest_collections(map: &mut serde_json::Map<String, serde_json::Value>) {
    if let Some(value) = map.get_mut("supportedstandards") {
        dedup_string_array(value);
    }
    if let Some(value) = map.get_mut("trusts") {
        dedup_string_array(value);
    }
    if let Some(value) = map.get_mut("permissions") {
        dedup_permissions(value);
    }
    if let Some(extra) = map.get_mut("abi").and_then(|abi| abi.as_object_mut()) {
        if let Some(methods) = extra.get_mut("methods") {
            dedup_method_offsets(methods);
        }
    }
}

fn dedup_string_array(value: &mut serde_json::Value) {
    if let Some(array) = value.as_array_mut() {
        let mut seen = HashSet::new();
        array.retain(|item| {
            if let Some(s) = item.as_str() {
                seen.insert(s.to_string())
            } else {
                true
            }
        });
    }
}

fn dedup_permissions(value: &mut serde_json::Value) {
    let Some(array) = value.as_array_mut() else {
        return;
    };

    let mut merged = Vec::new();
    let mut index_by_contract: HashMap<String, usize> = HashMap::new();
    let mut fallback_seen: HashSet<String> = HashSet::new();

    for mut entry in array.drain(..) {
        if let Some(contract) = entry
            .get("contract")
            .and_then(serde_json::Value::as_str)
            .map(|s| s.to_string())
        {
            let position = index_by_contract
                .entry(contract.clone())
                .or_insert_with(|| {
                    merged.push(serde_json::json!({
                        "contract": contract,
                        "methods": []
                    }));
                    merged.len() - 1
                });

            if let Some(methods) = entry.get_mut("methods") {
                merge_methods(&mut merged[*position], methods);
            }
        } else {
            let key = entry.to_string();
            if fallback_seen.insert(key) {
                merged.push(entry);
            }
        }
    }

    *array = merged;
}

fn merge_methods(target: &mut serde_json::Value, incoming: &serde_json::Value) {
    let Some(target_obj) = target.as_object_mut() else {
        return;
    };
    let Some(target_methods) = target_obj.get_mut("methods") else {
        return;
    };
    if !target_methods.is_array() {
        *target_methods = serde_json::Value::Array(Vec::new());
    }
    if let Some(array) = target_methods.as_array_mut() {
        if let Some(incoming_array) = incoming.as_array() {
            let mut seen: HashSet<String> = array
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
            for method in incoming_array {
                if let Some(name) = method.as_str() {
                    if seen.insert(name.to_string()) {
                        array.push(serde_json::Value::String(name.to_string()));
                    }
                }
            }
        }
    }
}

fn dedup_method_offsets(value: &mut serde_json::Value) {
    if let Some(items) = value.as_array_mut() {
        let mut merged: Vec<serde_json::Value> = Vec::new();
        let mut index_by_name: HashMap<String, usize> = HashMap::new();

        for entry in items.drain(..) {
            let method_name = entry
                .get("name")
                .and_then(serde_json::Value::as_str)
                .map(|s| s.to_string());

            if let Some(name) = method_name {
                if let Some(existing_index) = index_by_name.get(&name).copied() {
                    if let (Some(existing), Some(overlay)) =
                        (merged[existing_index].as_object_mut(), entry.as_object())
                    {
                        for (key, value) in overlay {
                            existing.insert(key.clone(), value.clone());
                        }
                    }
                    continue;
                }

                index_by_name.insert(name, merged.len());
                merged.push(entry);
            } else {
                merged.push(entry);
            }
        }

        *items = merged;
    }
}

#[cfg(test)]
mod tests {
    use super::{collect_method_names, ensure_manifest_methods_match, merge_manifest};
    use serde_json::json;
    use std::collections::HashSet;

    #[test]
    fn merge_manifest_deeply_combines_objects() {
        let mut base = json!({
            "abi": {
                "methods": ["foo"],
                "events": []
            },
            "extra": {
                "author": "neo-llvm"
            }
        });
        let overlay = json!({
            "abi": {
                "events": [
                    {"name": "Transfer", "parameters": []}
                ]
            },
            "supportedstandards": ["NEP-17"]
        });

        merge_manifest(&mut base, &overlay);

        assert_eq!(
            base["supportedstandards"].as_array().unwrap()[0]
                .as_str()
                .unwrap(),
            "NEP-17"
        );
        assert_eq!(base["abi"]["methods"].as_array().unwrap().len(), 1);
        assert_eq!(base["abi"]["events"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn merge_manifest_appends_arrays() {
        let mut base = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["foo"]}
            ],
            "abi": {
                "events": [
                    {"name": "First", "parameters": []}
                ]
            }
        });

        let overlay = json!({
            "permissions": [
                {"contract": "0x02", "methods": ["bar"]}
            ],
            "abi": {
                "events": [
                    {"name": "Second", "parameters": []}
                ]
            }
        });

        merge_manifest(&mut base, &overlay);

        let permissions = base["permissions"].as_array().unwrap();
        assert_eq!(permissions.len(), 2);
        assert_eq!(permissions[1]["contract"].as_str().unwrap(), "0x02");

        let events = base["abi"]["events"].as_array().unwrap();
        assert_eq!(events.len(), 2);
        assert_eq!(events[1]["name"].as_str().unwrap(), "Second");
    }

    #[test]
    fn merge_manifest_deduplicates_permissions_and_standards() {
        let mut base = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["a", "b"]}
            ],
            "supportedstandards": ["NEP-17"]
        });

        let overlay = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["b", "c"]},
                {"contract": "0x02", "methods": ["d"]}
            ],
            "supportedstandards": ["NEP-17", "NEP-11"]
        });

        merge_manifest(&mut base, &overlay);

        let permissions = base["permissions"].as_array().unwrap();
        assert_eq!(permissions.len(), 2);
        let methods = permissions[0]["methods"].as_array().unwrap();
        let method_set: std::collections::HashSet<_> =
            methods.iter().map(|v| v.as_str().unwrap()).collect();
        assert_eq!(method_set.len(), 3);
        assert!(method_set.contains("a"));
        assert!(method_set.contains("b"));
        assert!(method_set.contains("c"));

        let standards = base["supportedstandards"].as_array().unwrap();
        assert_eq!(standards.len(), 2);
    }

    #[test]
    fn collect_method_names_extracts_unique_set() {
        let manifest = json!({
            "abi": {
                "methods": [
                    {"name": "foo"},
                    {"name": "foo"},
                    {"name": "bar"}
                ]
            }
        });
        let names = collect_method_names(&manifest);
        assert_eq!(names.len(), 2);
        assert!(names.contains("foo"));
        assert!(names.contains("bar"));
    }

    #[test]
    fn ensure_manifest_methods_catches_added_entries() {
        let manifest = json!({
            "abi": { "methods": [
                {"name": "hello"},
                {"name": "ghost"}
            ]}
        });
        let baseline = HashSet::from(["hello".to_string()]);
        assert!(ensure_manifest_methods_match(&manifest, &baseline, Some("overlay.json")).is_err());
    }

    #[test]
    fn ensure_manifest_methods_catches_removed_entries() {
        let manifest = json!({
            "abi": { "methods": [
                {"name": "hello"}
            ]}
        });
        let baseline = HashSet::from(["hello".to_string(), "extra".to_string()]);
        assert!(ensure_manifest_methods_match(&manifest, &baseline, None).is_err());
    }
}

pub fn collect_method_names(manifest: &Value) -> HashSet<String> {
    manifest
        .get("abi")
        .and_then(|abi| abi.get("methods"))
        .and_then(Value::as_array)
        .map(|methods| {
            methods
                .iter()
                .filter_map(|method| method.get("name").and_then(Value::as_str))
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

pub fn ensure_manifest_methods_match(
    manifest: &Value,
    baseline: &HashSet<String>,
    overlay_label: Option<&str>,
) -> Result<()> {
    let final_names = collect_method_names(manifest);
    let mut introduced: Vec<String> = final_names.difference(baseline).cloned().collect();
    let mut missing: Vec<String> = baseline.difference(&final_names).cloned().collect();
    introduced.sort_unstable();
    missing.sort_unstable();

    if !introduced.is_empty() || !missing.is_empty() {
        let hint = overlay_label
            .map(|label| format!(" ({label})"))
            .unwrap_or_default();
        if !introduced.is_empty() {
            bail!(
                "manifest overlay{} introduced ABI methods that do not match the translated exports: {}",
                hint,
                introduced.join(", ")
            );
        }
        bail!(
            "manifest overlay{} removed exported ABI methods: {}",
            hint,
            missing.join(", ")
        );
    }

    Ok(())
}

#[derive(Debug)]
pub struct ManifestBuilder {
    manifest: Value,
    baseline_methods: HashSet<String>,
    overlay_label: Option<String>,
}

impl ManifestBuilder {
    pub fn new(name: &str, methods: &[ManifestMethod]) -> Self {
        let manifest = build_manifest(name, methods).value;
        ManifestBuilder {
            baseline_methods: collect_method_names(&manifest),
            manifest,
            overlay_label: None,
        }
    }

    pub fn merge_overlay(&mut self, overlay: &Value, label: Option<String>) {
        merge_manifest(&mut self.manifest, overlay);
        if let Some(label) = label {
            self.overlay_label = Some(label);
        }
    }

    pub fn propagate_safe_flags(&mut self) {
        propagate_safe_flags(&mut self.manifest);
    }

    pub fn ensure_method_parity(&self) -> Result<()> {
        ensure_manifest_methods_match(
            &self.manifest,
            &self.baseline_methods,
            self.overlay_label.as_deref(),
        )
    }

    pub fn manifest_value(&self) -> &Value {
        &self.manifest
    }

    pub fn manifest_value_mut(&mut self) -> &mut Value {
        &mut self.manifest
    }

    pub fn into_rendered(self) -> RenderedManifest {
        RenderedManifest {
            value: self.manifest,
        }
    }
}
