use serde::Serialize;
use serde_json::json;

#[derive(Debug, Clone, Serialize)]
pub struct ManifestParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ManifestMethod {
    pub name: String,
    pub parameters: Vec<ManifestParameter>,
    #[serde(rename = "returntype")]
    pub return_type: String,
    pub offset: u32,
    pub safe: bool,
}

#[derive(Debug, Clone)]
pub struct RenderedManifest {
    pub value: serde_json::Value,
}

impl RenderedManifest {
    pub fn to_string(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(&self.value)
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    let manifest = json!({
        "name": contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": [],
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": {
            "author": "neo-llvm",
            "description": "Generated by wasm-neovm translator",
        }
    });

    RenderedManifest { value: manifest }
}

pub fn merge_manifest(base: &mut serde_json::Value, overlay: &serde_json::Value) {
    if let (Some(base_map), Some(overlay_map)) = (base.as_object_mut(), overlay.as_object()) {
        for (key, value) in overlay_map {
            match base_map.get_mut(key) {
                Some(existing) => merge_manifest(existing, value),
                None => {
                    base_map.insert(key.clone(), value.clone());
                }
            }
        }
        return;
    }

    if let (Some(base_arr), Some(overlay_arr)) = (base.as_array_mut(), overlay.as_array()) {
        base_arr.extend(overlay_arr.iter().cloned());
        return;
    }

    *base = overlay.clone();
}

#[cfg(test)]
mod tests {
    use super::merge_manifest;
    use serde_json::json;

    #[test]
    fn merge_manifest_deeply_combines_objects() {
        let mut base = json!({
            "abi": {
                "methods": ["foo"],
                "events": []
            },
            "extra": {
                "author": "neo-llvm"
            }
        });
        let overlay = json!({
            "abi": {
                "events": [
                    {"name": "Transfer", "parameters": []}
                ]
            },
            "supportedstandards": ["NEP-17"]
        });

        merge_manifest(&mut base, &overlay);

        assert_eq!(
            base["supportedstandards"].as_array().unwrap()[0]
                .as_str()
                .unwrap(),
            "NEP-17"
        );
        assert_eq!(base["abi"]["methods"].as_array().unwrap().len(), 1);
        assert_eq!(base["abi"]["events"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn merge_manifest_appends_arrays() {
        let mut base = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["foo"]}
            ],
            "abi": {
                "events": [
                    {"name": "First", "parameters": []}
                ]
            }
        });

        let overlay = json!({
            "permissions": [
                {"contract": "0x02", "methods": ["bar"]}
            ],
            "abi": {
                "events": [
                    {"name": "Second", "parameters": []}
                ]
            }
        });

        merge_manifest(&mut base, &overlay);

        let permissions = base["permissions"].as_array().unwrap();
        assert_eq!(permissions.len(), 2);
        assert_eq!(permissions[1]["contract"].as_str().unwrap(), "0x02");

        let events = base["abi"]["events"].as_array().unwrap();
        assert_eq!(events.len(), 2);
        assert_eq!(events[1]["name"].as_str().unwrap(), "Second");
    }
}
