use serde::Serialize;
use serde_json::json;
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, Serialize)]
pub struct ManifestParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ManifestMethod {
    pub name: String,
    pub parameters: Vec<ManifestParameter>,
    #[serde(rename = "returntype")]
    pub return_type: String,
    pub offset: u32,
    pub safe: bool,
}

#[derive(Debug, Clone)]
pub struct RenderedManifest {
    pub value: serde_json::Value,
}

impl RenderedManifest {
    pub fn to_string(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(&self.value)
    }
}

pub fn build_manifest(contract_name: &str, methods: &[ManifestMethod]) -> RenderedManifest {
    let manifest = json!({
        "name": contract_name,
        "groups": [],
        "features": {},
        "supportedstandards": [],
        "permissions": [],
        "trusts": [],
        "abi": {
            "methods": methods,
            "events": [],
        },
        "extra": {
            "author": "neo-llvm",
            "description": "Generated by wasm-neovm translator",
        }
    });

    RenderedManifest { value: manifest }
}

pub fn merge_manifest(base: &mut serde_json::Value, overlay: &serde_json::Value) {
    if let (Some(base_map), Some(overlay_map)) = (base.as_object_mut(), overlay.as_object()) {
        for (key, value) in overlay_map {
            match base_map.get_mut(key) {
                Some(existing) => merge_manifest(existing, value),
                None => {
                    base_map.insert(key.clone(), value.clone());
                }
            }
        }
        dedup_manifest_collections(base_map);
        return;
    }

    if let (Some(base_arr), Some(overlay_arr)) = (base.as_array_mut(), overlay.as_array()) {
        base_arr.extend(overlay_arr.iter().cloned());
        return;
    }

    *base = overlay.clone();
}

pub fn propagate_safe_flags(manifest: &mut serde_json::Value) {
    let Some(abi) = manifest
        .get_mut("abi")
        .and_then(|value| value.as_object_mut())
    else {
        return;
    };
    let Some(methods) = abi
        .get_mut("methods")
        .and_then(|methods| methods.as_array_mut())
    else {
        return;
    };

    let mut safe_names: HashSet<String> = HashSet::new();
    for method in methods.iter() {
        if method
            .get("safe")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false)
        {
            if let Some(name) = method.get("name").and_then(serde_json::Value::as_str) {
                safe_names.insert(name.to_string());
            }
        }
    }

    if safe_names.is_empty() {
        return;
    }

    for method in methods.iter_mut() {
        if let Some(name) = method.get("name").and_then(serde_json::Value::as_str) {
            if safe_names.contains(name) {
                if let Some(obj) = method.as_object_mut() {
                    obj.insert("safe".to_string(), serde_json::Value::Bool(true));
                }
            }
        }
    }
}

fn dedup_manifest_collections(map: &mut serde_json::Map<String, serde_json::Value>) {
    if let Some(value) = map.get_mut("supportedstandards") {
        dedup_string_array(value);
    }
    if let Some(value) = map.get_mut("trusts") {
        dedup_string_array(value);
    }
    if let Some(value) = map.get_mut("permissions") {
        dedup_permissions(value);
    }
    if let Some(extra) = map.get_mut("abi").and_then(|abi| abi.as_object_mut()) {
        if let Some(methods) = extra.get_mut("methods") {
            dedup_method_offsets(methods);
        }
    }
}

fn dedup_string_array(value: &mut serde_json::Value) {
    if let Some(array) = value.as_array_mut() {
        let mut seen = HashSet::new();
        array.retain(|item| {
            if let Some(s) = item.as_str() {
                seen.insert(s.to_string())
            } else {
                true
            }
        });
    }
}

fn dedup_permissions(value: &mut serde_json::Value) {
    let Some(array) = value.as_array_mut() else {
        return;
    };

    let mut merged = Vec::new();
    let mut index_by_contract: HashMap<String, usize> = HashMap::new();
    let mut fallback_seen: HashSet<String> = HashSet::new();

    for mut entry in array.drain(..) {
        if let Some(contract) = entry
            .get("contract")
            .and_then(serde_json::Value::as_str)
            .map(|s| s.to_string())
        {
            let position = index_by_contract
                .entry(contract.clone())
                .or_insert_with(|| {
                    merged.push(serde_json::json!({
                        "contract": contract,
                        "methods": []
                    }));
                    merged.len() - 1
                });

            if let Some(methods) = entry.get_mut("methods") {
                merge_methods(&mut merged[*position], methods);
            }
        } else {
            let key = entry.to_string();
            if fallback_seen.insert(key) {
                merged.push(entry);
            }
        }
    }

    *array = merged;
}

fn merge_methods(target: &mut serde_json::Value, incoming: &serde_json::Value) {
    let Some(target_obj) = target.as_object_mut() else {
        return;
    };
    let Some(target_methods) = target_obj.get_mut("methods") else {
        return;
    };
    if !target_methods.is_array() {
        *target_methods = serde_json::Value::Array(Vec::new());
    }
    if let Some(array) = target_methods.as_array_mut() {
        if let Some(incoming_array) = incoming.as_array() {
            let mut seen: HashSet<String> = array
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
            for method in incoming_array {
                if let Some(name) = method.as_str() {
                    if seen.insert(name.to_string()) {
                        array.push(serde_json::Value::String(name.to_string()));
                    }
                }
            }
        }
    }
}

fn dedup_method_offsets(value: &mut serde_json::Value) {
    if let Some(items) = value.as_array_mut() {
        let mut seen = HashSet::new();
        items.retain(|item| {
            if let Some(name) = item
                .get("name")
                .and_then(serde_json::Value::as_str)
                .map(|s| s.to_string())
            {
                seen.insert(name)
            } else {
                true
            }
        });
    }
}

#[cfg(test)]
mod tests {
    use super::merge_manifest;
    use serde_json::json;

    #[test]
    fn merge_manifest_deeply_combines_objects() {
        let mut base = json!({
            "abi": {
                "methods": ["foo"],
                "events": []
            },
            "extra": {
                "author": "neo-llvm"
            }
        });
        let overlay = json!({
            "abi": {
                "events": [
                    {"name": "Transfer", "parameters": []}
                ]
            },
            "supportedstandards": ["NEP-17"]
        });

        merge_manifest(&mut base, &overlay);

        assert_eq!(
            base["supportedstandards"].as_array().unwrap()[0]
                .as_str()
                .unwrap(),
            "NEP-17"
        );
        assert_eq!(base["abi"]["methods"].as_array().unwrap().len(), 1);
        assert_eq!(base["abi"]["events"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn merge_manifest_appends_arrays() {
        let mut base = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["foo"]}
            ],
            "abi": {
                "events": [
                    {"name": "First", "parameters": []}
                ]
            }
        });

        let overlay = json!({
            "permissions": [
                {"contract": "0x02", "methods": ["bar"]}
            ],
            "abi": {
                "events": [
                    {"name": "Second", "parameters": []}
                ]
            }
        });

        merge_manifest(&mut base, &overlay);

        let permissions = base["permissions"].as_array().unwrap();
        assert_eq!(permissions.len(), 2);
        assert_eq!(permissions[1]["contract"].as_str().unwrap(), "0x02");

        let events = base["abi"]["events"].as_array().unwrap();
        assert_eq!(events.len(), 2);
        assert_eq!(events[1]["name"].as_str().unwrap(), "Second");
    }

    #[test]
    fn merge_manifest_deduplicates_permissions_and_standards() {
        let mut base = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["a", "b"]}
            ],
            "supportedstandards": ["NEP-17"]
        });

        let overlay = json!({
            "permissions": [
                {"contract": "0x01", "methods": ["b", "c"]},
                {"contract": "0x02", "methods": ["d"]}
            ],
            "supportedstandards": ["NEP-17", "NEP-11"]
        });

        merge_manifest(&mut base, &overlay);

        let permissions = base["permissions"].as_array().unwrap();
        assert_eq!(permissions.len(), 2);
        let methods = permissions[0]["methods"].as_array().unwrap();
        let method_set: std::collections::HashSet<_> =
            methods.iter().map(|v| v.as_str().unwrap()).collect();
        assert_eq!(method_set.len(), 3);
        assert!(method_set.contains("a"));
        assert!(method_set.contains("b"));
        assert!(method_set.contains("c"));

        let standards = base["supportedstandards"].as_array().unwrap();
        assert_eq!(standards.len(), 2);
    }
}
