use super::NeoVMSyscallInfo;

/// Neo N3 System Calls
pub const SYSCALLS: &[NeoVMSyscallInfo] = &[
    NeoVMSyscallInfo {
        name: "System.Contract.Call",
        hash: 0x525b7d62,
        parameters: &["Hash160", "String", "Integer", "Array"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.CallNative",
        hash: 0x677bf71a,
        parameters: &["Integer"],
        return_type: "Void",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.CreateMultisigAccount",
        hash: 0x09e9336a,
        parameters: &["Integer", "Array"],
        return_type: "Hash160",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.CreateStandardAccount",
        hash: 0x028799cf,
        parameters: &["ByteString"],
        return_type: "Hash160",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.GetCallFlags",
        hash: 0x813ada95,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 1024,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.NativeOnPersist",
        hash: 0x93bcdb2e,
        parameters: &[],
        return_type: "Void",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Contract.NativePostPersist",
        hash: 0x165da144,
        parameters: &[],
        return_type: "Void",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Crypto.CheckMultisig",
        hash: 0x3adcd09e,
        parameters: &["Array", "Array"],
        return_type: "Boolean",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Crypto.CheckSig",
        hash: 0x27b3e756,
        parameters: &["ByteString", "ByteString"],
        return_type: "Boolean",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Iterator.Next",
        hash: 0x9ced089c,
        parameters: &["Iterator"],
        return_type: "Boolean",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Iterator.Value",
        hash: 0x1dbf54f3,
        parameters: &["Iterator"],
        return_type: "StackItem",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.BurnGas",
        hash: 0xbc8c5ac3,
        parameters: &["Integer"],
        return_type: "Void",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.CheckWitness",
        hash: 0x8cec27f8,
        parameters: &["ByteString"],
        return_type: "Boolean",
        gas_cost: 1024,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.CurrentSigners",
        hash: 0x8b18f1ac,
        parameters: &[],
        return_type: "Array",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GasLeft",
        hash: 0xced88814,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetAddressVersion",
        hash: 0xdc92494c,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetCallingScriptHash",
        hash: 0x3c6e5339,
        parameters: &[],
        return_type: "Hash160",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetEntryScriptHash",
        hash: 0x38e2b4f9,
        parameters: &[],
        return_type: "Hash160",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetExecutingScriptHash",
        hash: 0x74a8fedb,
        parameters: &[],
        return_type: "Hash160",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetInvocationCounter",
        hash: 0x43112784,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetNetwork",
        hash: 0xe0a0fbc5,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetNotifications",
        hash: 0xf1354327,
        parameters: &["Hash160"],
        return_type: "Array",
        gas_cost: 4096,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetRandom",
        hash: 0x28a9de6b,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 0,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetScriptContainer",
        hash: 0x3008512d,
        parameters: &[],
        return_type: "StackItem",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetTime",
        hash: 0x0388c3b7,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.GetTrigger",
        hash: 0xa0387de9,
        parameters: &[],
        return_type: "Integer",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.LoadScript",
        hash: 0x8f800cb3,
        parameters: &["ByteString", "Integer", "Array"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.Log",
        hash: 0x9647e7cf,
        parameters: &["ByteString"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.Notify",
        hash: 0x616f0195,
        parameters: &["ByteString", "Array"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Runtime.Platform",
        hash: 0xf6fc79b2,
        parameters: &[],
        return_type: "String",
        gas_cost: 8,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.AsReadOnly",
        hash: 0xe9bf4c76,
        parameters: &["StorageContext"],
        return_type: "StorageContext",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.Delete",
        hash: 0xedc5582f,
        parameters: &["StorageContext", "ByteString"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.Find",
        hash: 0x9ab830df,
        parameters: &["StorageContext", "ByteString", "Integer"],
        return_type: "Iterator",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.Get",
        hash: 0x31e85d92,
        parameters: &["StorageContext", "ByteString"],
        return_type: "ByteString",
        gas_cost: 32768,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.GetContext",
        hash: 0xce67f69b,
        parameters: &[],
        return_type: "StorageContext",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.GetReadOnlyContext",
        hash: 0xe26bb4f6,
        parameters: &[],
        return_type: "StorageContext",
        gas_cost: 16,
        description: "",
    },
    NeoVMSyscallInfo {
        name: "System.Storage.Put",
        hash: 0x84183fe6,
        parameters: &["StorageContext", "ByteString", "ByteString"],
        return_type: "Void",
        gas_cost: 32768,
        description: "",
    },
];
