// Copyright (c) 2025 R3E Network
// Licensed under the MIT License

use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use serde_json::json;
use syn::{
    DeriveInput, Fields, FnArg, GenericArgument, ImplItem, ImplItemFn, Item, ItemFn, ItemImpl,
    LitStr, Pat, PatIdent, PathArguments, ReturnType, Type,
};

use crate::codegen;

pub(crate) fn neo_contract(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl ::neo_devpack::NeoContract for #name {
            fn name() -> &'static str {
                stringify!(#name)
            }

            fn version() -> &'static str {
                "1.0.0"
            }

            fn author() -> &'static str {
                "neo-devpack"
            }

            fn description() -> &'static str {
                "Neo N3 smart contract generated by neo-devpack"
            }
        }
    }
}

pub(crate) fn neo_contract_item(input: Item) -> syn::Result<TokenStream2> {
    match input {
        Item::Struct(item_struct) => {
            let derived: DeriveInput = syn::parse2(quote!(#item_struct))?;
            Ok(neo_contract(derived))
        }
        Item::Impl(item_impl) => neo_contract_impl(item_impl),
        other => Err(syn::Error::new_spanned(
            other,
            "#[neo_contract] supports structs and impl blocks",
        )),
    }
}

fn neo_contract_impl(input: ItemImpl) -> syn::Result<TokenStream2> {
    let contract_ty = (*input.self_ty).clone();
    let exported = collect_export_methods(&input)?;

    let wrappers = exported
        .into_iter()
        .map(|method| method.wrapper_tokens(&contract_ty))
        .collect::<syn::Result<Vec<_>>>()?;

    Ok(quote! {
        #input
        #(#wrappers)*
    })
}

struct ExportedMethod {
    method_ident: syn::Ident,
    export_ident: syn::Ident,
    wrapper_inputs: Vec<TokenStream2>,
    call_args: Vec<TokenStream2>,
    has_receiver: bool,
    mutable_receiver: bool,
    output_kind: ExportOutputKind,
    safe: bool,
}

enum ExportOutputKind {
    ResultNeoInteger,
    ResultNeoBoolean,
    ResultVoid,
    NeoInteger,
    NeoBoolean,
    I64,
    Bool,
    Void,
}

impl ExportedMethod {
    fn wrapper_tokens(self, contract_ty: &Type) -> syn::Result<TokenStream2> {
        let ExportedMethod {
            method_ident,
            export_ident,
            wrapper_inputs,
            call_args,
            has_receiver,
            mutable_receiver,
            output_kind,
            safe,
        } = self;

        let safe_attr = if safe {
            quote! { #[::neo_devpack::neo_safe] }
        } else {
            quote! {}
        };

        let invoke = if has_receiver {
            if mutable_receiver {
                quote! {
                    let mut __contract = #contract_ty::new();
                    __contract.#method_ident(#(#call_args),*)
                }
            } else {
                quote! {
                    let __contract = #contract_ty::new();
                    __contract.#method_ident(#(#call_args),*)
                }
            }
        } else {
            quote! {
                #contract_ty::#method_ident(#(#call_args),*)
            }
        };

        let (wrapper_output, body) = match output_kind {
            ExportOutputKind::ResultNeoInteger => (
                quote! { i64 },
                quote! {
                    match { #invoke } {
                        Ok(value) => value.as_i32_saturating() as i64,
                        Err(_) => 0i64,
                    }
                },
            ),
            ExportOutputKind::ResultNeoBoolean => (
                quote! { i64 },
                quote! {
                    match { #invoke } {
                        Ok(value) => {
                            if value.as_bool() {
                                1i64
                            } else {
                                0i64
                            }
                        }
                        Err(_) => 0i64,
                    }
                },
            ),
            ExportOutputKind::ResultVoid => (
                quote! { () },
                quote! {
                    let _ = { #invoke };
                },
            ),
            ExportOutputKind::NeoInteger => (
                quote! { i64 },
                quote! {
                    { #invoke }.as_i32_saturating() as i64
                },
            ),
            ExportOutputKind::NeoBoolean => (
                quote! { i64 },
                quote! {
                    if { #invoke }.as_bool() {
                        1i64
                    } else {
                        0i64
                    }
                },
            ),
            ExportOutputKind::I64 => (
                quote! { i64 },
                quote! {
                    { #invoke }
                },
            ),
            ExportOutputKind::Bool => (
                quote! { i64 },
                quote! {
                    if { #invoke } {
                        1i64
                    } else {
                        0i64
                    }
                },
            ),
            ExportOutputKind::Void => (
                quote! { () },
                quote! {
                    { #invoke };
                },
            ),
        };

        Ok(quote! {
            #safe_attr
            #[no_mangle]
            pub extern "C" fn #export_ident(#(#wrapper_inputs),*) -> #wrapper_output {
                #body
            }
        })
    }
}

#[derive(Default)]
struct NeoMethodConfig {
    safe: bool,
    export_name: Option<String>,
}

fn collect_export_methods(item_impl: &ItemImpl) -> syn::Result<Vec<ExportedMethod>> {
    let mut methods = Vec::new();

    for item in &item_impl.items {
        let ImplItem::Fn(method) = item else {
            continue;
        };

        let Some(config) = parse_neo_method_config(&method.attrs)? else {
            continue;
        };

        let (has_receiver, mutable_receiver, wrapper_inputs, call_args) =
            parse_method_inputs(method)?;

        let output_kind = parse_output_kind(&method.sig.output)?;

        let export_name = config
            .export_name
            .unwrap_or_else(|| snake_to_camel(&method.sig.ident.to_string()));
        let export_ident = syn::parse_str::<syn::Ident>(&export_name).map_err(|_| {
            syn::Error::new(
                method.sig.ident.span(),
                format!("Invalid export name `{export_name}` generated for #[neo_method]"),
            )
        })?;

        methods.push(ExportedMethod {
            method_ident: method.sig.ident.clone(),
            export_ident,
            wrapper_inputs,
            call_args,
            has_receiver,
            mutable_receiver,
            output_kind,
            safe: config.safe,
        });
    }

    Ok(methods)
}

fn parse_neo_method_config(attrs: &[syn::Attribute]) -> syn::Result<Option<NeoMethodConfig>> {
    for attr in attrs {
        if !attr.path().is_ident("neo_method") {
            continue;
        }

        let mut config = NeoMethodConfig::default();

        if matches!(attr.meta, syn::Meta::List(_)) {
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("safe") {
                    config.safe = true;
                    return Ok(());
                }

                if meta.path.is_ident("name") || meta.path.is_ident("export_name") {
                    let value = meta.value()?;
                    let lit: LitStr = value.parse()?;
                    config.export_name = Some(lit.value());
                    return Ok(());
                }

                Err(meta.error("unsupported #[neo_method] option; use `safe` or `name = \"...\"`"))
            })?;
        }

        return Ok(Some(config));
    }

    Ok(None)
}

fn parse_method_inputs(
    method: &ImplItemFn,
) -> syn::Result<(bool, bool, Vec<TokenStream2>, Vec<TokenStream2>)> {
    let mut has_receiver = false;
    let mut mutable_receiver = false;
    let mut wrapper_inputs = Vec::new();
    let mut call_args = Vec::new();

    for input in &method.sig.inputs {
        match input {
            FnArg::Receiver(receiver) => {
                has_receiver = true;
                mutable_receiver = receiver.mutability.is_some();
            }
            FnArg::Typed(typed) => {
                let ident = parse_ident_pattern(&typed.pat)?;
                let conversion = argument_conversion(&typed.ty, &ident)?;
                wrapper_inputs.push(quote! { #ident: i64 });
                call_args.push(conversion);
            }
        }
    }

    Ok((has_receiver, mutable_receiver, wrapper_inputs, call_args))
}

fn parse_ident_pattern(pattern: &Pat) -> syn::Result<syn::Ident> {
    match pattern {
        Pat::Ident(PatIdent { ident, .. }) => Ok(ident.clone()),
        _ => Err(syn::Error::new_spanned(
            pattern,
            "#[neo_method] parameters must be simple identifiers",
        )),
    }
}

fn argument_conversion(ty: &Type, ident: &syn::Ident) -> syn::Result<TokenStream2> {
    let Some(type_ident) = type_ident(ty) else {
        return Err(syn::Error::new_spanned(
            ty,
            "Unsupported #[neo_method] argument type",
        ));
    };

    match type_ident.to_string().as_str() {
        "NeoInteger" => Ok(quote! { ::neo_devpack::NeoInteger::new(#ident) }),
        "NeoBoolean" => Ok(quote! { ::neo_devpack::NeoBoolean::new(#ident != 0) }),
        "i64" => Ok(quote! { #ident }),
        "bool" => Ok(quote! { #ident != 0 }),
        unsupported => Err(syn::Error::new_spanned(
            ty,
            format!(
                "Unsupported #[neo_method] argument type `{unsupported}` for auto-export wrappers"
            ),
        )),
    }
}

fn parse_output_kind(output: &ReturnType) -> syn::Result<ExportOutputKind> {
    let return_type = match output {
        ReturnType::Default => {
            return Ok(ExportOutputKind::Void);
        }
        ReturnType::Type(_, ty) => ty,
    };

    let Some(top_ident) = type_ident(return_type) else {
        return Err(syn::Error::new_spanned(
            return_type,
            "Unsupported #[neo_method] return type",
        ));
    };

    if top_ident == "NeoResult" {
        let Type::Path(type_path) = return_type.as_ref() else {
            return Err(syn::Error::new_spanned(
                return_type,
                "NeoResult return type must be a path",
            ));
        };

        let Some(segment) = type_path.path.segments.last() else {
            return Err(syn::Error::new_spanned(
                type_path,
                "Invalid NeoResult return type",
            ));
        };

        let PathArguments::AngleBracketed(arguments) = &segment.arguments else {
            return Err(syn::Error::new_spanned(
                segment,
                "NeoResult must include a concrete inner return type",
            ));
        };

        let Some(GenericArgument::Type(inner_type)) = arguments.args.first() else {
            return Err(syn::Error::new_spanned(
                arguments,
                "NeoResult inner return type is required",
            ));
        };

        let inner = parse_inner_output_kind(inner_type)?;
        return Ok(match inner {
            ExportOutputKind::NeoInteger => ExportOutputKind::ResultNeoInteger,
            ExportOutputKind::NeoBoolean => ExportOutputKind::ResultNeoBoolean,
            ExportOutputKind::Void => ExportOutputKind::ResultVoid,
            _ => {
                return Err(syn::Error::new_spanned(
                    inner_type,
                    "Unsupported nested NeoResult return type",
                ));
            }
        });
    }

    parse_inner_output_kind(return_type)
}

fn parse_inner_output_kind(ty: &Type) -> syn::Result<ExportOutputKind> {
    if let Type::Tuple(tuple) = ty {
        if tuple.elems.is_empty() {
            return Ok(ExportOutputKind::Void);
        }
    }

    let Some(inner_ident) = type_ident(ty) else {
        return Err(syn::Error::new_spanned(
            ty,
            "Unsupported #[neo_method] return type for auto-export wrappers",
        ));
    };

    match inner_ident.to_string().as_str() {
        "NeoInteger" => Ok(ExportOutputKind::NeoInteger),
        "NeoBoolean" => Ok(ExportOutputKind::NeoBoolean),
        "i64" => Ok(ExportOutputKind::I64),
        "bool" => Ok(ExportOutputKind::Bool),
        unsupported => Err(syn::Error::new_spanned(
            ty,
            format!(
                "Unsupported #[neo_method] return type `{unsupported}` for auto-export wrappers"
            ),
        )),
    }
}

fn type_ident(ty: &Type) -> Option<&syn::Ident> {
    match ty {
        Type::Path(type_path) => type_path.path.segments.last().map(|segment| &segment.ident),
        Type::Reference(reference) => type_ident(&reference.elem),
        _ => None,
    }
}

fn snake_to_camel(name: &str) -> String {
    let mut output = String::with_capacity(name.len());
    let mut uppercase_next = false;

    for ch in name.chars() {
        if ch == '_' {
            uppercase_next = true;
            continue;
        }

        if uppercase_next {
            output.extend(ch.to_uppercase());
            uppercase_next = false;
        } else {
            output.push(ch);
        }
    }

    output
}
pub(crate) fn neo_method(input: ItemFn) -> TokenStream2 {
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;

    quote! {
        #vis #sig #block
    }
}

pub(crate) fn neo_storage(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;
    let storage_key = format!("{}::storage", name);

    quote! {
        #input

        impl #name {
            /// Load storage with error handling.
            ///
            /// # Note on Name Collisions
            /// If your struct already has a `load_result` method, you may encounter
            /// compilation errors. In that case, manually implement the storage logic
            /// or rename your existing method.
            pub fn load_result(
                context: &::neo_devpack::NeoStorageContext,
            ) -> ::neo_devpack::NeoResult<Self>
            where
                Self: ::core::default::Default
                    + ::neo_devpack::serde::de::DeserializeOwned,
            {
                let key = ::neo_devpack::NeoByteString::from_slice(#storage_key.as_bytes());
                let bytes = ::neo_devpack::NeoStorage::get(context, &key)?;
                if bytes.is_empty() {
                    return Ok(Self::default());
                }
                ::neo_devpack::codec::deserialize(bytes.as_slice())
            }

            /// Load storage, returning default on error.
            ///
            /// # Note on Name Collisions
            /// If your struct already has a `load` method, you may encounter
            /// compilation errors. Use `load_result` directly or rename your method.
            pub fn load(
                context: &::neo_devpack::NeoStorageContext,
            ) -> Self
            where
                Self: ::core::default::Default
                    + ::neo_devpack::serde::de::DeserializeOwned,
            {
                Self::load_result(context).unwrap_or_else(|_| Self::default())
            }

            /// Save to storage.
            ///
            /// # Note on Name Collisions
            /// If your struct already has a `save` method, you may encounter
            /// compilation errors. Implement storage manually or rename your method.
            pub fn save(
                &self,
                context: &::neo_devpack::NeoStorageContext,
            ) -> ::neo_devpack::NeoResult<()>
            where
                Self: ::neo_devpack::serde::Serialize,
            {
                if context.is_read_only() {
                    return Err(::neo_devpack::NeoError::InvalidOperation);
                }
                let key = ::neo_devpack::NeoByteString::from_slice(#storage_key.as_bytes());
                let bytes = ::neo_devpack::codec::serialize(self)?;
                let payload = ::neo_devpack::NeoByteString::new(bytes);
                ::neo_devpack::NeoStorage::put(context, &key, &payload)
            }
        }
    }
}

pub(crate) fn neo_entry(input: ItemFn) -> TokenStream2 {
    let entry_name = input.sig.ident.to_string();
    let kind = entry_name.as_str();

    let metadata = serde_json::json!({
        "entry": {
            "name": entry_name,
            "kind": kind,
        }
    });
    let overlay = codegen::manifest_overlay_tokens(&metadata.to_string());

    quote! {
        #input
        #overlay
    }
}

pub(crate) fn neo_test(input: ItemFn) -> TokenStream2 {
    let name = &input.sig.ident;
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;
    let test_mod = format_ident!("__neo_test_{}", name);
    let test_fn = format_ident!("{}_case", name);

    quote! {
        #vis #sig #block

        #[cfg(test)]
        mod #test_mod {
            use super::*;

            #[test]
            fn #test_fn() {
                super::#name()
            }
        }
    }
}

pub(crate) fn neo_bench(input: ItemFn) -> TokenStream2 {
    let name = &input.sig.ident;
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;
    let bench_mod = format_ident!("__neo_bench_{}", name);

    quote! {
        #vis #sig #block

        #[cfg(feature = "bench")]
        mod #bench_mod {
            use super::*;
            use criterion::*;

            fn run(c: &mut Criterion) {
                c.bench_function(stringify!(#name), |b| {
                    b.iter(|| {
                        super::#name()
                    });
                });
            }

            criterion_group!(benches, run);
            criterion_main!(benches);
        }
    }
}

pub(crate) fn neo_event(input: DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let fields = match &input.data {
        syn::Data::Struct(struct_data) => match &struct_data.fields {
            Fields::Named(named) => named.named.iter().collect::<Vec<_>>(),
            Fields::Unnamed(_) | Fields::Unit => {
                return Err(syn::Error::new_spanned(
                    &input,
                    "#[neo_event] requires a struct with named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                &input,
                "#[neo_event] can only be applied to structs",
            ));
        }
    };

    let push_fields = fields.iter().map(|field| {
        let ident = field.ident.as_ref().ok_or_else(|| {
            syn::Error::new_spanned(field, "expected named field")
        })?;
        Ok(quote! {
            state.push(::neo_devpack::NeoValue::from(::core::clone::Clone::clone(&self.#ident)));
        })
    }).collect::<syn::Result<Vec<_>>>()?;

    let event_name_string = name.to_string();
    let parameters: Vec<serde_json::Value> = fields
        .iter()
        .map(|field| {
            let field_name = field
                .ident
                .as_ref()
                .map(|i| i.to_string())
                .unwrap_or_else(|| "unnamed".to_string());
            let manifest_type = codegen::manifest_type_from_syn(&field.ty);
            json!({
                "name": field_name,
                "type": manifest_type,
            })
        })
        .collect();
    let metadata = json!({
        "abi": {
            "events": [
                {
                    "name": event_name_string,
                    "parameters": parameters,
                }
            ]
        }
    });
    let overlay = codegen::manifest_overlay_tokens(&metadata.to_string());

    Ok(quote! {
        #input

        impl #name {
            pub fn emit(&self) -> ::neo_devpack::NeoResult<()> {
                let event_name = stringify!(#name);
                let mut state = ::neo_devpack::NeoArray::new();
                #(#push_fields)*
                let label = ::neo_devpack::NeoString::from_str(event_name);
                ::neo_devpack::NeoRuntime::notify(&label, &state)
            }
        }

        #overlay
    })
}

pub(crate) fn neo_manifest_overlay(literal: &LitStr) -> TokenStream2 {
    let value = literal.value();

    if let Err(err) = serde_json::from_str::<serde_json::Value>(&value) {
        return syn::Error::new(literal.span(), format!("invalid JSON: {err}")).to_compile_error();
    }

    codegen::manifest_overlay_tokens(&value)
}

pub(crate) fn neo_permission(contract: String, methods: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "permissions": [
            {
                "contract": contract,
                "methods": methods,
            }
        ]
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_trusts(trusts: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "trusts": trusts,
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_safe_methods(methods: Vec<String>) -> TokenStream2 {
    let methods: Vec<serde_json::Value> = methods
        .into_iter()
        .map(|name| json!({"name": name, "safe": true}))
        .collect();

    let overlay = json!({
        "abi": { "methods": methods }
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_safe(input: ItemFn) -> TokenStream2 {
    let name = input.sig.ident.to_string();

    let overlay = json!({
        "abi": { "methods": [ { "name": name, "safe": true } ] }
    });

    let overlay_tokens = codegen::manifest_overlay_tokens(&overlay.to_string());

    quote! {
        #input
        #overlay_tokens
    }
}

pub(crate) fn neo_supported_standards(standards: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "supportedstandards": standards,
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_doc(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl #name {
            pub fn documentation() -> &'static str {
                "Neo N3 smart contract documentation"
            }
        }
    }
}

pub(crate) fn neo_config(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    // Extract field names from the struct to avoid assuming specific field names
    let fields = match &input.data {
        syn::Data::Struct(struct_data) => match &struct_data.fields {
            Fields::Named(named) => named.named.iter().collect::<Vec<_>>(),
            _ => {
                return syn::Error::new_spanned(
                    &input,
                    "#[neo_config] requires a struct with named fields",
                )
                .to_compile_error();
            }
        },
        _ => {
            return syn::Error::new_spanned(&input, "#[neo_config] can only be applied to structs")
                .to_compile_error();
        }
    };

    // Generate field initializations based on type
    let field_inits = fields.iter().map(|field| {
        let ident = field
            .ident
            .as_ref()
            .expect("#[neo_config] macro only supports named struct fields");
        let field_name = ident.to_string();

        // Generate appropriate default based on field name pattern
        let init_expr = if field_name.contains("max") {
            quote! { ::neo_devpack::NeoInteger::max_i32() }
        } else if field_name.contains("min") {
            quote! { ::neo_devpack::NeoInteger::min_i32() }
        } else {
            // For unknown fields, use Default::default()
            quote! { ::core::default::Default::default() }
        };

        quote! { #ident: #init_expr }
    });

    quote! {
        #input

        impl ::core::default::Default for #name {
            fn default() -> Self {
                Self {
                    #(#field_inits),*
                }
            }
        }

        impl #name {
            /// Load configuration with default values.
            /// Override this method to implement custom loading logic.
            pub fn load() -> ::neo_devpack::NeoResult<Self> {
                Ok(Self::default())
            }

            /// Save configuration.
            /// Override this method to implement custom saving logic.
            pub fn save(&self) -> ::neo_devpack::NeoResult<()> {
                Ok(())
            }
        }
    }
}

pub(crate) fn neo_validate(input: ItemFn) -> TokenStream2 {
    quote! { #input }
}

pub(crate) fn neo_serialize(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl #name {
            pub fn serialize(&self) -> ::neo_devpack::NeoResult<::neo_devpack::NeoByteString> {
                let bytes = ::neo_devpack::codec::serialize(self)?;
                Ok(::neo_devpack::NeoByteString::new(bytes))
            }

            pub fn deserialize(
                data: &::neo_devpack::NeoByteString,
            ) -> ::neo_devpack::NeoResult<Self> {
                ::neo_devpack::codec::deserialize(data.as_slice())
            }
        }
    }
}

pub(crate) fn neo_error(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl ::core::convert::From<#name> for ::neo_devpack::NeoError {
            fn from(_: #name) -> Self {
                ::neo_devpack::NeoError::InvalidArgument
            }
        }

        impl #name {
            pub fn as_neo_error(&self) -> ::neo_devpack::NeoError {
                ::neo_devpack::NeoError::InvalidArgument
            }
        }
    }
}
