use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use serde_json::json;
use syn::{DeriveInput, Fields, ItemFn, LitStr};

use crate::codegen;

pub(crate) fn neo_contract(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl ::neo_devpack::NeoContract for #name {
            fn name() -> &'static str {
                stringify!(#name)
            }

            fn version() -> &'static str {
                "1.0.0"
            }

            fn author() -> &'static str {
                "neo-devpack"
            }

            fn description() -> &'static str {
                "Neo N3 smart contract generated by neo-devpack"
            }
        }
    }
}

pub(crate) fn neo_method(input: ItemFn) -> TokenStream2 {
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;

    quote! {
        #vis #sig #block
    }
}

pub(crate) fn neo_storage(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;
    let storage_key = format!("{}::storage", name);

    quote! {
        #input

        impl #name {
            pub fn load_result(
                context: &::neo_devpack::NeoStorageContext,
            ) -> ::neo_devpack::NeoResult<Self>
            where
                Self: ::core::default::Default
                    + ::neo_devpack::serde::de::DeserializeOwned,
            {
                let key = ::neo_devpack::NeoByteString::from_slice(#storage_key.as_bytes());
                let bytes = ::neo_devpack::NeoStorage::get(context, &key)?;
                if bytes.is_empty() {
                    return Ok(Self::default());
                }
                ::neo_devpack::codec::deserialize(bytes.as_slice())
            }

            pub fn load(
                context: &::neo_devpack::NeoStorageContext,
            ) -> Self
            where
                Self: ::core::default::Default
                    + ::neo_devpack::serde::de::DeserializeOwned,
            {
                Self::load_result(context).unwrap_or_else(|_| Self::default())
            }

            pub fn save(
                &self,
                context: &::neo_devpack::NeoStorageContext,
            ) -> ::neo_devpack::NeoResult<()>
            where
                Self: ::neo_devpack::serde::Serialize,
            {
                if context.is_read_only() {
                    return Err(::neo_devpack::NeoError::InvalidOperation);
                }
                let key = ::neo_devpack::NeoByteString::from_slice(#storage_key.as_bytes());
                let bytes = ::neo_devpack::codec::serialize(self)?;
                let payload = ::neo_devpack::NeoByteString::new(bytes);
                ::neo_devpack::NeoStorage::put(context, &key, &payload)
            }
        }
    }
}

pub(crate) fn neo_entry(input: ItemFn) -> TokenStream2 {
    let entry_name = input.sig.ident.to_string();
    let kind = match entry_name.as_str() {
        "deploy" => "deploy",
        "update" => "update",
        "destroy" => "destroy",
        other => other,
    };

    let metadata = serde_json::json!({
        "entry": {
            "name": entry_name,
            "kind": kind,
        }
    });
    let overlay = codegen::manifest_overlay_tokens(&metadata.to_string());

    quote! {
        #input
        #overlay
    }
}

pub(crate) fn neo_test(input: ItemFn) -> TokenStream2 {
    let name = &input.sig.ident;
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;
    let test_mod = format_ident!("__neo_test_{}", name);
    let test_fn = format_ident!("{}_case", name);

    quote! {
        #vis #sig #block

        #[cfg(test)]
        mod #test_mod {
            use super::*;

            #[test]
            fn #test_fn() {
                super::#name()
            }
        }
    }
}

pub(crate) fn neo_bench(input: ItemFn) -> TokenStream2 {
    let name = &input.sig.ident;
    let vis = &input.vis;
    let sig = &input.sig;
    let block = &input.block;
    let bench_mod = format_ident!("__neo_bench_{}", name);

    quote! {
        #vis #sig #block

        #[cfg(feature = "bench")]
        mod #bench_mod {
            use super::*;
            use criterion::*;

            fn run(c: &mut Criterion) {
                c.bench_function(stringify!(#name), |b| {
                    b.iter(|| {
                        super::#name()
                    });
                });
            }

            criterion_group!(benches, run);
            criterion_main!(benches);
        }
    }
}

pub(crate) fn neo_event(input: DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let fields = match &input.data {
        syn::Data::Struct(struct_data) => match &struct_data.fields {
            Fields::Named(named) => named.named.iter().collect::<Vec<_>>(),
            Fields::Unnamed(_) | Fields::Unit => {
                return Err(syn::Error::new_spanned(
                    &input,
                    "#[neo_event] requires a struct with named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                &input,
                "#[neo_event] can only be applied to structs",
            ));
        }
    };

    let push_fields = fields.iter().map(|field| {
        let ident = field.ident.as_ref().expect("named field");
        quote! {
            state.push(::neo_devpack::NeoValue::from(::core::clone::Clone::clone(&self.#ident)));
        }
    });

    let event_name_string = name.to_string();
    let parameters: Vec<serde_json::Value> = fields
        .iter()
        .map(|field| {
            let field_name = field.ident.as_ref().unwrap().to_string();
            let manifest_type = codegen::manifest_type_from_syn(&field.ty);
            json!({
                "name": field_name,
                "type": manifest_type,
            })
        })
        .collect();
    let metadata = json!({
        "abi": {
            "events": [
                {
                    "name": event_name_string,
                    "parameters": parameters,
                }
            ]
        }
    });
    let overlay = codegen::manifest_overlay_tokens(&metadata.to_string());

    Ok(quote! {
        #input

        impl #name {
            pub fn emit(&self) -> ::neo_devpack::NeoResult<()> {
                let event_name = stringify!(#name);
                let mut state = ::neo_devpack::NeoArray::new();
                #(#push_fields)*
                let label = ::neo_devpack::NeoString::from_str(event_name);
                ::neo_devpack::NeoRuntime::notify(&label, &state)
            }
        }

        #overlay
    })
}

pub(crate) fn neo_manifest_overlay(literal: &LitStr) -> TokenStream2 {
    let value = literal.value();

    if let Err(err) = serde_json::from_str::<serde_json::Value>(&value) {
        return syn::Error::new(literal.span(), format!("invalid JSON: {err}"))
            .to_compile_error();
    }

    codegen::manifest_overlay_tokens(&value)
}

pub(crate) fn neo_permission(contract: String, methods: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "permissions": [
            {
                "contract": contract,
                "methods": methods,
            }
        ]
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_trusts(trusts: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "trusts": trusts,
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_safe_methods(methods: Vec<String>) -> TokenStream2 {
    let methods: Vec<serde_json::Value> = methods
        .into_iter()
        .map(|name| json!({"name": name, "safe": true}))
        .collect();

    let overlay = json!({
        "abi": { "methods": methods }
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_safe(input: ItemFn) -> TokenStream2 {
    let name = input.sig.ident.to_string();

    let overlay = json!({
        "abi": { "methods": [ { "name": name, "safe": true } ] }
    });

    let overlay_tokens = codegen::manifest_overlay_tokens(&overlay.to_string());

    quote! {
        #input
        #overlay_tokens
    }
}

pub(crate) fn neo_supported_standards(standards: Vec<String>) -> TokenStream2 {
    let overlay = json!({
        "supportedstandards": standards,
    });

    codegen::manifest_overlay_tokens(&overlay.to_string())
}

pub(crate) fn neo_doc(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl #name {
            pub fn documentation() -> &'static str {
                "Neo N3 smart contract documentation"
            }
        }
    }
}

pub(crate) fn neo_config(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl ::core::default::Default for #name {
            fn default() -> Self {
                Self {
                    max_value: ::neo_devpack::NeoInteger::max_i32(),
                    min_value: ::neo_devpack::NeoInteger::min_i32(),
                }
            }
        }

        impl #name {
            pub fn load() -> ::neo_devpack::NeoResult<Self> {
                Ok(Self::default())
            }

            pub fn save(&self) -> ::neo_devpack::NeoResult<()> {
                Ok(())
            }
        }
    }
}

pub(crate) fn neo_validate(input: ItemFn) -> TokenStream2 {
    quote! { #input }
}

pub(crate) fn neo_serialize(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl #name {
            pub fn serialize(&self) -> ::neo_devpack::NeoResult<::neo_devpack::NeoByteString> {
                let bytes = ::neo_devpack::codec::serialize(self)?;
                Ok(::neo_devpack::NeoByteString::new(bytes))
            }

            pub fn deserialize(
                data: &::neo_devpack::NeoByteString,
            ) -> ::neo_devpack::NeoResult<Self> {
                ::neo_devpack::codec::deserialize(data.as_slice())
            }
        }
    }
}

pub(crate) fn neo_error(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;

    quote! {
        #input

        impl ::core::convert::From<#name> for ::neo_devpack::NeoError {
            fn from(_: #name) -> Self {
                ::neo_devpack::NeoError::InvalidArgument
            }
        }

        impl #name {
            pub fn as_neo_error(&self) -> ::neo_devpack::NeoError {
                ::neo_devpack::NeoError::InvalidArgument
            }
        }
    }
}

