// AUTO-GENERATED by gen_exprs (seed=1, count=80, depth=8, nodes=26). Do not edit.
#![allow(clippy::all, unused_parens, unused_variables, dead_code)]
use neo_devpack::prelude::*;
#[inline] fn gdiv(x: i64, y: i64) -> i64 { x.checked_div(y).unwrap_or(0) }
#[inline] fn grem(x: i64, y: i64) -> i64 { x.checked_rem(y).unwrap_or(0) }
#[inline] fn gdivu(x: i64, y: i64) -> i64 { if y == 0 { 0 } else { ((x as u64) / (y as u64)) as i64 } }
pub const GEN_COUNT: i64 = 80;
#[inline(never)] pub fn g0(a: i64, b: i64) -> i64 { ((((((gdivu((b).wrapping_mul((((a) as u64).wrapping_shr((((((((b).wrapping_abs())) as u64) < ((((b).wrapping_neg())) as u64)) as i64)) as u32) as i64)), (((((((b).wrapping_abs())) < (a)) as i64)).wrapping_abs()))).min(((((((gdiv((((((9223372036854775807i64).wrapping_shr((2147483648i64) as u32)) as u64) < ((4454276479544968717i64) as u64)) as i64), a)).count_ones() as i64)) as u64) < ((-2570648721579178915i64) as u64)) as i64)))).min(a))).min(b)) }
#[inline(never)] pub fn g1(a: i64, b: i64) -> i64 { (((((((NeoInteger::new((((((a) == ((((a).wrapping_sub(b)) | ((((-4823490714494750339i64) as i32) as i64))))) as i64)).wrapping_neg())) >> (((gdiv((((((((b) as i32) as i64)) as u32) as u64 as i64)).wrapping_shr((b) as u32), grem(gdiv(4251471980962470017i64, 0i64), -783257373892236320i64))) & 63) as u32)).as_i64_saturating())).count_ones() as i64)).wrapping_abs())).wrapping_add(((-256i64) & (b))) }
#[inline(never)] pub fn g2(a: i64, b: i64) -> i64 { ((((!(((grem(gdiv((((((a).count_ones() as i64)) ^ ((a).wrapping_sub(256i64)))).wrapping_mul(((a) | (((3081806217630438848i64).min(256i64))))), ((((a) ^ (((a).wrapping_neg())))).wrapping_neg())), (((gdiv(((b) & (-7858110849043999734i64)), a)) as i32) as i64))) ^ (2345519320372471732i64))))) < (b)) as i64) }
#[inline(never)] pub fn g3(a: i64, b: i64) -> i64 { (((!(((((((((((((!(b))) as u32) as u64 as i64)).count_ones() as i64)).wrapping_sub(b)) | ((((a).rotate_left(((((((((NeoInteger::new(8i64) | NeoInteger::new(-1352603814869947859i64)).as_i64_saturating())) as u64) < ((((((b) as u64) < ((a) as u64)) as i64)) as u64)) as i64)) & 63) as u32))).wrapping_mul((if (b) != 0 { ((((-256i64).wrapping_neg())).min(-7078743181068454542i64)) } else { b }))))) == (b)) as i64)))).count_ones() as i64) }
#[inline(never)] pub fn g4(a: i64, b: i64) -> i64 { ((((((((((((NeoInteger::new((((b).wrapping_add(1286116353243596044i64)).wrapping_abs())) >> (((gdivu((((9223372036854775807i64) as i8) as i64), (-1330972541818387224i64).wrapping_shr((a) as u32))) & 63) as u32)).as_i64_saturating())).count_ones() as i64)) & (((((if (((((b).wrapping_sub(b)) as i32) as i64)) != 0 { ((63i64).wrapping_neg()) } else { ((NeoInteger::new(5115692469096106657i64) * NeoInteger::new(8i64)).as_i64_saturating()) })) as i8) as i64)))).wrapping_neg())) as i32) as i64)).wrapping_shl((b) as u32) }
#[inline(never)] pub fn g5(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g6(a: i64, b: i64) -> i64 { ((-4749229876217660158i64).count_ones() as i64) }
#[inline(never)] pub fn g7(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g8(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g9(a: i64, b: i64) -> i64 { ((((NeoInteger::new((((((((32i64).wrapping_add(((NeoInteger::new(((NeoInteger::new(b) & NeoInteger::new(b)).as_i64_saturating())) * NeoInteger::new(((a).min(b)))).as_i64_saturating()))).wrapping_neg())) ^ (((((((b).wrapping_sub(-7710872247987188296i64)) as i8) as i64)) | ((((b) as i32) as i64)))))).max(grem((if ((((a).wrapping_abs())).wrapping_shr((b) as u32)) != 0 { 64i64 } else { a }), b)))) >> (((31i64) & 63) as u32)).as_i64_saturating())) | (b)) }
#[inline(never)] pub fn g10(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g11(a: i64, b: i64) -> i64 { ((gdivu(((grem(((((((((NeoInteger::new(b) + NeoInteger::new((((a) as u32) as u64 as i64))).as_i64_saturating())) as u64) < (((((((b).max(-7731156505130217406i64))) as i8) as i64)) as u64)) as i64)) ^ ((((((-8552390334067138344i64) as u64) < (((((b) as i8) as i64)) as u64)) as i64)).wrapping_shr((((((a).wrapping_neg())).count_ones() as i64)) as u32))), grem(b, (((-835388168778484718i64) as i32) as i64)))).wrapping_abs()), 3950791776611597514i64)).wrapping_neg()) }
#[inline(never)] pub fn g12(a: i64, b: i64) -> i64 { (((((a).min(((NeoInteger::new(b) >> (((gdiv(((NeoInteger::new(a) | NeoInteger::new(grem(((b).min(-6249783736498523732i64)), ((((b) as u64) < ((b) as u64)) as i64)))).as_i64_saturating()), ((gdivu((if (-9006278129394161197i64) != 0 { a } else { b }), (a).wrapping_shr((4913663306496844637i64) as u32))).min(b)))) & 63) as u32)).as_i64_saturating())))).wrapping_shr((3379114280326045286i64) as u32)).rotate_left(((b) & 63) as u32)) }
#[inline(never)] pub fn g13(a: i64, b: i64) -> i64 { ((NeoInteger::new(((((((NeoInteger::new((if (a) != 0 { ((((NeoInteger::new(a) >> (((a) & 63) as u32)).as_i64_saturating())).wrapping_neg()) } else { (((((b).wrapping_sub(2865616453792482107i64)) as u64) < ((((((a) as u64) < ((b) as u64)) as i64)) as u64)) as i64) })) * NeoInteger::new(a)).as_i64_saturating())) ^ (((if ((((b) == (gdivu(b, 6256785146998155754i64))) as i64)) != 0 { -4700351804530199320i64 } else { b })).wrapping_shr((a) as u32)))).wrapping_mul(a)).wrapping_shl((b) as u32)) ^ NeoInteger::new(-2873438218534004028i64)).as_i64_saturating()) }
#[inline(never)] pub fn g14(a: i64, b: i64) -> i64 { ((((NeoInteger::new((2i64).wrapping_mul(((2154596871547534699i64).rotate_left(((((((b).wrapping_abs())).max((((((b) & (-1i64))) < ((!(a)))) as i64)))) & 63) as u32)))) >> ((((((((NeoInteger::new(((((a).wrapping_neg())) ^ (((((if (b) != 0 { a } else { 8910838460081377385i64 })) as i32) as i64)))) >> (((b) & 63) as u32)).as_i64_saturating())) as i32) as i64)) & 63) as u32)).as_i64_saturating())).wrapping_shl((-6300056450649459009i64) as u32)).wrapping_sub(-1588221394506421898i64) }
#[inline(never)] pub fn g15(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g16(a: i64, b: i64) -> i64 { ((((a) as u32) as u64 as i64)).wrapping_mul(a) }
#[inline(never)] pub fn g17(a: i64, b: i64) -> i64 { (((((((((((((((gdiv(a, -8513976507683698222i64)) == ((((a) < (4682901161717132588i64)) as i64))) as i64)).wrapping_add(((((b).wrapping_neg())).min(gdiv(2i64, 2147483647i64))))).min(grem((((-256i64) as i8) as i64), 7i64)))).wrapping_add(-3014212943249763136i64)) as u64).wrapping_shr((((a) & (8i64))) as u32) as i64)).wrapping_neg())) as u64).wrapping_shr((b) as u32) as i64) }
#[inline(never)] pub fn g18(a: i64, b: i64) -> i64 { gdiv(a, (if (a) != 0 { ((3540690588322961634i64) & (((((!((((((1403721295773909157i64) as i32) as i64)) & (4294967295i64))))) as u64).wrapping_shr((gdiv(gdiv((((a).min(a))).wrapping_mul((((a) < (b)) as i64)), b), (if ((a).wrapping_sub(b)) != 0 { -6453502631511064776i64 } else { b }))) as u32) as i64))) } else { a })) }
#[inline(never)] pub fn g19(a: i64, b: i64) -> i64 { 6177955787639230856i64 }
#[inline(never)] pub fn g20(a: i64, b: i64) -> i64 { ((((gdivu(((((((((((-5877432030335974382i64).wrapping_shl((-9223372036854775808i64) as u32)).count_ones() as i64)) ^ (((((((a) as u64).wrapping_shr((b) as u32) as i64)) as i8) as i64)))) as i32) as i64)).wrapping_neg()), (((a).wrapping_shr(((((a) as i32) as i64)) as u32)).wrapping_abs()))).wrapping_mul(grem(b, (((((((!(b))) as u64) < ((b) as u64)) as i64)).count_ones() as i64)))) == (1i64)) as i64) }
#[inline(never)] pub fn g21(a: i64, b: i64) -> i64 { ((((((((a) as u64) < ((((a) & (((NeoInteger::new((b).wrapping_add(a)) ^ NeoInteger::new(((gdivu(((-8364748799620718259i64).wrapping_abs()), ((-5524239692530227602i64) & (b)))).min(b)))).as_i64_saturating())))) as u64)) as i64)).max((((4294967295i64) < (3257168733820902684i64)) as i64)))) ^ ((((a) < (grem(((-1220955761522900880i64) & (a)), -8151932704693668071i64))) as i64))) }
#[inline(never)] pub fn g22(a: i64, b: i64) -> i64 { ((!(4497465995622577722i64))).wrapping_sub(((NeoInteger::new(-1i64) ^ NeoInteger::new(64i64)).as_i64_saturating())) }
#[inline(never)] pub fn g23(a: i64, b: i64) -> i64 { ((((a) as u32) as u64 as i64)).wrapping_shr(((((((((a) == (((4795986354427218528i64).count_ones() as i64))) as i64)) as u64).wrapping_shr((2335557196111575928i64) as u32) as i64)).wrapping_shl(((((((((((((!(((NeoInteger::new(b) & NeoInteger::new(b)).as_i64_saturating())))) == ((((((a).wrapping_neg())) < (a)) as i64))) as i64)) ^ (1938398271945567315i64))).wrapping_abs())) as i32) as i64)) as u32)) as u32) }
#[inline(never)] pub fn g24(a: i64, b: i64) -> i64 { gdivu(-4526098981143455958i64, a) }
#[inline(never)] pub fn g25(a: i64, b: i64) -> i64 { (a).wrapping_shr((((b).rotate_left(((((((grem(a, grem(((a) | ((32i64).wrapping_mul(((a) | (b))))), 8i64))) as u64) < ((((a).min(((NeoInteger::new((((((8009502032881487662i64) & (a))) == ((((2147483648i64) == (b)) as i64))) as i64)) & NeoInteger::new(6832265756621916264i64)).as_i64_saturating())))) as u64)) as i64)) & 63) as u32))) as u32) }
#[inline(never)] pub fn g26(a: i64, b: i64) -> i64 { -6246233483270082381i64 }
#[inline(never)] pub fn g27(a: i64, b: i64) -> i64 { ((((((((((((((!((7172643768156758500i64).wrapping_shl((b) as u32)))).wrapping_neg())).wrapping_shl((grem(gdiv((((a) as i8) as i64), 3307404129133002947i64), ((grem(a, -256i64)) & ((((8111328584132668640i64) < (-6243631937608264784i64)) as i64))))) as u32)) as u64) < ((gdivu(((((b).wrapping_neg())).wrapping_abs()), b)) as u64)) as i64)) as i32) as i64)).wrapping_mul(b)) & (2i64)) }
#[inline(never)] pub fn g28(a: i64, b: i64) -> i64 { (((((((((NeoInteger::new((((a) == (((((4611686018427387904i64) & (a))).wrapping_add(b)).wrapping_sub((((-8410552526052473072i64) == ((((b) < (a)) as i64))) as i64)))) as i64)) | NeoInteger::new(a)).as_i64_saturating())) as u64) < (((((b) as i8) as i64)) as u64)) as i64)).wrapping_shl(((((((((a) as i8) as i64)).wrapping_mul(((NeoInteger::new(64i64) ^ NeoInteger::new(b)).as_i64_saturating()))) as i8) as i64)) as u32)).max(8351018322917440005i64)) }
#[inline(never)] pub fn g29(a: i64, b: i64) -> i64 { ((((((if (a) != 0 { -8726758567815513850i64 } else { 423063075264965855i64 })).min(((((grem(((NeoInteger::new((((grem(256i64, 413075253055857156i64)) == (b)) as i64)) & NeoInteger::new(b)).as_i64_saturating()), ((NeoInteger::new(2792166066425206727i64) >> (((a) & 63) as u32)).as_i64_saturating()))) as u32) as u64 as i64)).wrapping_shr((((((NeoInteger::new(((((((6784751987340632800i64) as i32) as i64)).wrapping_shl((-8921661916804838152i64) as u32)) | (b))) >> (((b) & 63) as u32)).as_i64_saturating())).wrapping_neg())) as u32)))) as i32) as i64) }
#[inline(never)] pub fn g30(a: i64, b: i64) -> i64 { ((NeoInteger::new(a) & NeoInteger::new(gdivu((gdivu(gdivu(((((gdiv(2147483647i64, b)) < (((a) & (a)))) as i64)).wrapping_add(b), a), (if (b) != 0 { ((NeoInteger::new(((-4330727316239461468i64).min(((NeoInteger::new(-7334162172394790102i64) >> (((a) & 63) as u32)).as_i64_saturating())))) >> ((((((-2178062832837803687i64) as i8) as i64)) & 63) as u32)).as_i64_saturating()) } else { a }))).wrapping_mul(a), b))).as_i64_saturating()) }
#[inline(never)] pub fn g31(a: i64, b: i64) -> i64 { ((NeoInteger::new(((((NeoInteger::new(a) >> (((((((((b) as u64).wrapping_shr((b) as u32) as i64)) as i8) as i64)) & 63) as u32)).as_i64_saturating())).wrapping_neg())) >> (((grem((((((((((((((((-7849332746447407816i64) as u32) as u64 as i64)) | (((2i64).rotate_left(((a) & 63) as u32))))) as i8) as i64)).wrapping_shl((((((((((a) as i32) as i64)) as i32) as i64)).count_ones() as i64)) as u32)) < (((NeoInteger::new(((b).min(b))) + NeoInteger::new(b)).as_i64_saturating()))) as i64)) as u64).wrapping_shr((b) as u32) as i64), b)) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g32(a: i64, b: i64) -> i64 { ((((((((a) < (((((((((b) as i8) as i64)) < ((((((((256i64).wrapping_abs())).wrapping_abs())) as u64).wrapping_shr(((b).wrapping_mul(b)) as u32) as i64))) as i64)).wrapping_neg()))) as i64)).wrapping_neg())) as u64).wrapping_shr(((((((b) as u32) as u64 as i64)) & ((((b) as i32) as i64)))) as u32) as i64) }
#[inline(never)] pub fn g33(a: i64, b: i64) -> i64 { 8i64 }
#[inline(never)] pub fn g34(a: i64, b: i64) -> i64 { ((NeoInteger::new(1i64) - NeoInteger::new(((gdivu(gdivu(3350733209974900453i64, a), gdivu(8i64, (((((((1628853486772306553i64).wrapping_add(((b).rotate_left(((b) & 63) as u32)))) as u64) < (((((a) ^ (b))).wrapping_add((a).wrapping_shl((-837654266377465874i64) as u32))) as u64)) as i64)) | ((((4132220246161033076i64).wrapping_add(a)).min(a))))))).max(b)))).as_i64_saturating()) }
#[inline(never)] pub fn g35(a: i64, b: i64) -> i64 { (((3061249979811515173i64).wrapping_mul((((b) as i8) as i64))).wrapping_abs()) }
#[inline(never)] pub fn g36(a: i64, b: i64) -> i64 { ((((!((((b).wrapping_sub((((b) as i8) as i64))).wrapping_mul(((((if (grem(a, b)) != 0 { (b).wrapping_add(31i64) } else { (((4294967295i64) as u32) as u64 as i64) })) as u32) as u64 as i64))).wrapping_mul((1439492542629717515i64).wrapping_shl((((((((b) < (b)) as i64)).wrapping_sub(2510509919656517913i64)).rotate_left(((b) & 63) as u32))) as u32))))).max(-2392738255548200626i64))).wrapping_shl((b) as u32) }
#[inline(never)] pub fn g37(a: i64, b: i64) -> i64 { ((((((((((b).wrapping_shl(((((if (((((b) as u64) < ((1499061437488590268i64) as u64)) as i64)) != 0 { (!(2147483647i64)) } else { ((b) ^ (-4338499335670084006i64)) })) & (grem(((NeoInteger::new(b) >> (((b) & 63) as u32)).as_i64_saturating()), ((-4615349057962775162i64).wrapping_abs()))))) as u32)).count_ones() as i64)).wrapping_sub((((((-2042854850428906385i64).rotate_left(((a) & 63) as u32))).wrapping_shr((b) as u32)).wrapping_neg()))) == (b)) as i64)) as u32) as u64 as i64) }
#[inline(never)] pub fn g38(a: i64, b: i64) -> i64 { ((((((((((((NeoInteger::new(gdivu(((b).wrapping_shl((a) as u32)).wrapping_add((((a) < (1i64)) as i64)), (((((b) < (b)) as i64)).count_ones() as i64))) & NeoInteger::new(((((if ((b).wrapping_shr((9223372036854775807i64) as u32)) != 0 { a } else { (b).wrapping_mul(a) })) as i8) as i64))).as_i64_saturating())) < (b)) as i64)).wrapping_neg())) < (a)) as i64)).wrapping_abs()) }
#[inline(never)] pub fn g39(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g40(a: i64, b: i64) -> i64 { ((b).rotate_left(((((((((((((((((((b) as u32) as u64 as i64)).wrapping_neg())) & (((a).wrapping_abs())))) as u64).wrapping_shr((((b).wrapping_neg())) as u32) as i64)).wrapping_shr((a) as u32)).count_ones() as i64)) as i8) as i64)) & 63) as u32)) }
#[inline(never)] pub fn g41(a: i64, b: i64) -> i64 { 3279797504940058604i64 }
#[inline(never)] pub fn g42(a: i64, b: i64) -> i64 { ((((((a) | ((((a) < (8672800584248692257i64)) as i64)))).wrapping_add(((b) | (-4843496910849928588i64)))) as i8) as i64) }
#[inline(never)] pub fn g43(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g44(a: i64, b: i64) -> i64 { ((NeoInteger::new((((((((((NeoInteger::new((!((b).wrapping_shr((b) as u32)))) >> (((a) & 63) as u32)).as_i64_saturating())).wrapping_add(gdivu(b, ((a).wrapping_add(a)).wrapping_sub(((1055825608255615836i64).min(a)))))).min(((255i64).count_ones() as i64)))) ^ ((((((((((a).max(b))) as i32) as i64)) as u64) < ((a) as u64)) as i64)))) | (b))) >> (((-8553631159979565472i64) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g45(a: i64, b: i64) -> i64 { 4611686018427387904i64 }
#[inline(never)] pub fn g46(a: i64, b: i64) -> i64 { ((((NeoInteger::new(a) >> ((((((((b).wrapping_neg())) < (((((((((((NeoInteger::new((((-256i64) as i32) as i64)) >> ((((1327303841050773441i64).wrapping_shl((b) as u32)) & 63) as u32)).as_i64_saturating())) ^ (((NeoInteger::new(a) >> ((((if (a) != 0 { a } else { 2341970674617391771i64 })) & 63) as u32)).as_i64_saturating())))) as u32) as u64 as i64)) as u32) as u64 as i64))) as i64)) & 63) as u32)).as_i64_saturating())).count_ones() as i64) }
#[inline(never)] pub fn g47(a: i64, b: i64) -> i64 { ((((NeoInteger::new((((((a).wrapping_add(((((NeoInteger::new(a) >> (((((a).wrapping_neg())) & 63) as u32)).as_i64_saturating())) & (b)))).rotate_left(((-4734606901980082756i64) & 63) as u32))).max((((b) < (((b).max(((((NeoInteger::new(gdivu(3598581626815885100i64, a)) + NeoInteger::new(b)).as_i64_saturating())).rotate_left(((gdiv(((b).wrapping_abs()), 31i64)) & 63) as u32)))))) as i64)))) >> (((2147483648i64) & 63) as u32)).as_i64_saturating())).wrapping_abs()) }
#[inline(never)] pub fn g48(a: i64, b: i64) -> i64 { 2i64 }
#[inline(never)] pub fn g49(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g50(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g51(a: i64, b: i64) -> i64 { (!((((((((NeoInteger::new(((if (((((((b) as i32) as i64)) < (b)) as i64)) != 0 { (((b).max(2936337578408639663i64))).wrapping_shl((((((6624700146465741832i64) as u64) < ((a) as u64)) as i64)) as u32) } else { (((((NeoInteger::new(a) >> (((9162027635100100735i64) & 63) as u32)).as_i64_saturating())) as i8) as i64) })).wrapping_sub(grem(b, gdiv(b, b)))) >> (((-957939333894592820i64) & 63) as u32)).as_i64_saturating())) as u64).wrapping_shr((7480001143133081637i64) as u32) as i64)).wrapping_abs()))) }
#[inline(never)] pub fn g52(a: i64, b: i64) -> i64 { ((b).min(((((((((((-8021876633803821253i64).wrapping_shr((((((6964974362813512880i64) as u64) < ((a) as u64)) as i64)) as u32)) & ((((6902328707359394879i64).wrapping_shl((2271250016960651099i64) as u32)) & (((NeoInteger::new(b) * NeoInteger::new(a)).as_i64_saturating())))))) & ((((((((a).count_ones() as i64)).min((((b) == (b)) as i64)))) == (b)) as i64)))) as i8) as i64)).wrapping_mul(a)).wrapping_shl((b) as u32))) }
#[inline(never)] pub fn g53(a: i64, b: i64) -> i64 { gdivu(((NeoInteger::new((((grem((((((((((-2147483648i64) as i8) as i64)).count_ones() as i64)).wrapping_neg())) & (a)), a)) as i8) as i64)) >> ((((-1i64).wrapping_mul((!((if (b) != 0 { 8i64 } else { ((NeoInteger::new(((((!(a))) < ((-7800483745186788161i64).wrapping_shr((b) as u32))) as i64)) & NeoInteger::new((((b) == (b)) as i64))).as_i64_saturating()) }))))) & 63) as u32)).as_i64_saturating()), b) }
#[inline(never)] pub fn g54(a: i64, b: i64) -> i64 { 2147483648i64 }
#[inline(never)] pub fn g55(a: i64, b: i64) -> i64 { (((((NeoInteger::new(((-6190632303355542387i64).wrapping_shl((6674896943222438101i64) as u32)).wrapping_shr((a) as u32)) >> (((6714617575580405387i64) & 63) as u32)).as_i64_saturating())) < (((8i64) ^ (((b).min((((((((((((b).min(3003846506834953315i64))).max(((a).max(b))))) | (((-330251932685011995i64).count_ones() as i64)))).wrapping_shl((((b) & (8149900816217167789i64))) as u32)) as u64) < ((b) as u64)) as i64))))))) as i64) }
#[inline(never)] pub fn g56(a: i64, b: i64) -> i64 { (if (((((((((((((8249136141584352254i64).wrapping_mul(((a).max(256i64)))).max(a))) as u64).wrapping_shr((((((((a) as u64).wrapping_shr((-56784890565597165i64) as u32) as i64)) ^ (((b) | (a))))).wrapping_mul(((NeoInteger::new((8482687838309014709i64).wrapping_mul(b)) | NeoInteger::new(gdiv(b, b))).as_i64_saturating()))) as u32) as i64)).rotate_left(((a) & 63) as u32))).wrapping_shr((a) as u32)) as i32) as i64)) != 0 { 2147483647i64 } else { -2591799041372363548i64 }) }
#[inline(never)] pub fn g57(a: i64, b: i64) -> i64 { (!((((((((((((a) < (((((b) | (b))).min(b)))) as i64)).wrapping_mul((((((!(b))).wrapping_neg())).min(b)))).max((a).wrapping_mul(a)))).count_ones() as i64)) as u64).wrapping_shr((((((((2521441750919227215i64).rotate_left(((((a).rotate_left(((b) & 63) as u32))) & 63) as u32))) == (1296911169748562156i64)) as i64)).wrapping_shr((a) as u32)) as u32) as i64))) }
#[inline(never)] pub fn g58(a: i64, b: i64) -> i64 { grem(a, ((NeoInteger::new(((((if ((gdiv(31i64, a)).wrapping_shl((((((((b) as i32) as i64)) as u32) as u64 as i64)) as u32)) != 0 { ((b) ^ (gdivu((b).wrapping_add(a), (((2809785134364953427i64) as i8) as i64)))) } else { ((((a).wrapping_mul(4078584782631574925i64)).wrapping_abs())).wrapping_shr((-256i64) as u32) })).wrapping_shr((a) as u32)) & (-1759468378093961309i64))) * NeoInteger::new(a)).as_i64_saturating())) }
#[inline(never)] pub fn g59(a: i64, b: i64) -> i64 { ((8056150211370744411i64).count_ones() as i64) }
#[inline(never)] pub fn g60(a: i64, b: i64) -> i64 { (((((if ((((((((NeoInteger::new((((((((NeoInteger::new(4043496237935413065i64) - NeoInteger::new(a)).as_i64_saturating())).wrapping_add((((b) as u32) as u64 as i64))) as u64) < (((if ((((-4942412204854903935i64) as i32) as i64)) != 0 { ((1430197576095009819i64).count_ones() as i64) } else { ((b) ^ (b)) })) as u64)) as i64)) & NeoInteger::new((((((((((4692088047836575333i64).min(b))) as i8) as i64)) as u64) < ((b) as u64)) as i64))).as_i64_saturating())) as i8) as i64)).min(b))) != 0 { a } else { a })) as u64) < ((1i64) as u64)) as i64) }
#[inline(never)] pub fn g61(a: i64, b: i64) -> i64 { (((((((a).wrapping_shl((((((((((-3039831162324073355i64) == (a)) as i64)) ^ (b))).wrapping_shr(((((b) & (b))).wrapping_shr((gdivu(a, a)) as u32)) as u32)) ^ ((a).wrapping_add((((((-256i64) == (b)) as i64)).max(a)))))) as u32)).max(a))).wrapping_add(b)) as i8) as i64) }
#[inline(never)] pub fn g62(a: i64, b: i64) -> i64 { (((a).wrapping_sub(((b) ^ ((((!((((if (((-7600857757660198387i64).wrapping_neg())) != 0 { (5879231557675200465i64).wrapping_mul(a) } else { (((b) as i32) as i64) })) ^ (((a).wrapping_abs())))))).rotate_left(((a) & 63) as u32)))))).count_ones() as i64) }
#[inline(never)] pub fn g63(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g64(a: i64, b: i64) -> i64 { 4773793268997590584i64 }
#[inline(never)] pub fn g65(a: i64, b: i64) -> i64 { -958816573473570612i64 }
#[inline(never)] pub fn g66(a: i64, b: i64) -> i64 { ((a).min(gdivu((((((63i64).wrapping_abs())).wrapping_neg())).wrapping_shl((((grem(gdiv(((-256i64) | (((((4611686018427387904i64) as u64) < ((a) as u64)) as i64))), b), (((((((2147483647i64).max(3474202350627468662i64))).wrapping_abs())) as i8) as i64))).max(2147483647i64))) as u32), ((((((a).count_ones() as i64)).min(-4771442207205146110i64))).count_ones() as i64)))) }
#[inline(never)] pub fn g67(a: i64, b: i64) -> i64 { (((((((((((((NeoInteger::new((((a) as u64).wrapping_shr((b) as u32) as i64)) ^ NeoInteger::new(((((((b) as i32) as i64)) as i8) as i64))).as_i64_saturating())) as i8) as i64)).max(((NeoInteger::new(b) >> ((((((grem(a, (!(b)))).min(7771774337817900405i64))).wrapping_sub((((gdivu(a, -2147483648i64)).wrapping_shl((b) as u32)) ^ (a)))) & 63) as u32)).as_i64_saturating())))) as u32) as u64 as i64)) as i8) as i64) }
#[inline(never)] pub fn g68(a: i64, b: i64) -> i64 { (((((gdivu(b, (((((a).min(4036513287757881178i64))) < (64i64)) as i64))).count_ones() as i64)) as i32) as i64) }
#[inline(never)] pub fn g69(a: i64, b: i64) -> i64 { ((NeoInteger::new((a).wrapping_sub(-5112108757057966i64)) | NeoInteger::new(((b).rotate_left((((((((-3878093777660893026i64) as u32) as u64 as i64)).max((((((((((NeoInteger::new(-5818190056598604183i64) >> ((((((b) as i8) as i64)) & 63) as u32)).as_i64_saturating())) < (((((-4232287274431951203i64).wrapping_neg())).count_ones() as i64))) as i64)).wrapping_mul(a)) as u32) as u64 as i64)))) & 63) as u32)))).as_i64_saturating()) }
#[inline(never)] pub fn g70(a: i64, b: i64) -> i64 { ((-8555246545341388003i64).max(((-1202739692721965785i64).count_ones() as i64))) }
#[inline(never)] pub fn g71(a: i64, b: i64) -> i64 { ((((a) as u64) < ((((b).wrapping_neg())) as u64)) as i64) }
#[inline(never)] pub fn g72(a: i64, b: i64) -> i64 { 31i64 }
#[inline(never)] pub fn g73(a: i64, b: i64) -> i64 { ((a) | (((((((b).wrapping_abs())).count_ones() as i64)).count_ones() as i64))) }
#[inline(never)] pub fn g74(a: i64, b: i64) -> i64 { ((((((((((((((((((5360470749355958929i64).min(a))).wrapping_add((a).wrapping_shr((a) as u32))) as u32) as u64 as i64)).wrapping_abs())) as u64) < (((((gdiv(((b) | ((b).wrapping_mul(a))), a)) < ((((((((b).wrapping_shr((b) as u32)) as i8) as i64)) as i32) as i64))) as i64)) as u64)) as i64)) ^ (b))) & (3942192089445123335i64))).min(5814465710460349653i64)) }
#[inline(never)] pub fn g75(a: i64, b: i64) -> i64 { 4611686018427387904i64 }
#[inline(never)] pub fn g76(a: i64, b: i64) -> i64 { ((b) | (((((grem(((NeoInteger::new(b) >> (((((((((3994627361386755300i64).wrapping_shl((b) as u32)) as u64).wrapping_shr((grem(5916708539545773994i64, -1063464118962876671i64)) as u32) as i64)).max((((((a).max(a))) as i32) as i64)))) & 63) as u32)).as_i64_saturating()), b)) as i8) as i64)).wrapping_mul(gdiv(a, (31i64).wrapping_shr((((b).rotate_left(((63i64) & 63) as u32))) as u32))))) }
#[inline(never)] pub fn g77(a: i64, b: i64) -> i64 { ((NeoInteger::new(((((b).wrapping_shl(((a).wrapping_shl(((!((((((b) as i32) as i64)).wrapping_neg())))) as u32)) as u32)).wrapping_mul(gdiv((((((((((((((b) as u64) < ((b) as u64)) as i64)) as u64) < ((((a) & (31i64))) as u64)) as i64)) ^ (((((-4499858399078868624i64).wrapping_add(8838597647244788490i64)) as i8) as i64)))) as i32) as i64), b))) & (a))) >> (((2i64) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g78(a: i64, b: i64) -> i64 { (((0i64) as i8) as i64) }
#[inline(never)] pub fn g79(a: i64, b: i64) -> i64 { ((((b).wrapping_abs())) & (((a).max((((b) as u32) as u64 as i64))))) }
pub fn eval_idx(idx: i64, a: i64, b: i64) -> i64 {
    match idx {
        0 => g0(a, b),
        1 => g1(a, b),
        2 => g2(a, b),
        3 => g3(a, b),
        4 => g4(a, b),
        5 => g5(a, b),
        6 => g6(a, b),
        7 => g7(a, b),
        8 => g8(a, b),
        9 => g9(a, b),
        10 => g10(a, b),
        11 => g11(a, b),
        12 => g12(a, b),
        13 => g13(a, b),
        14 => g14(a, b),
        15 => g15(a, b),
        16 => g16(a, b),
        17 => g17(a, b),
        18 => g18(a, b),
        19 => g19(a, b),
        20 => g20(a, b),
        21 => g21(a, b),
        22 => g22(a, b),
        23 => g23(a, b),
        24 => g24(a, b),
        25 => g25(a, b),
        26 => g26(a, b),
        27 => g27(a, b),
        28 => g28(a, b),
        29 => g29(a, b),
        30 => g30(a, b),
        31 => g31(a, b),
        32 => g32(a, b),
        33 => g33(a, b),
        34 => g34(a, b),
        35 => g35(a, b),
        36 => g36(a, b),
        37 => g37(a, b),
        38 => g38(a, b),
        39 => g39(a, b),
        40 => g40(a, b),
        41 => g41(a, b),
        42 => g42(a, b),
        43 => g43(a, b),
        44 => g44(a, b),
        45 => g45(a, b),
        46 => g46(a, b),
        47 => g47(a, b),
        48 => g48(a, b),
        49 => g49(a, b),
        50 => g50(a, b),
        51 => g51(a, b),
        52 => g52(a, b),
        53 => g53(a, b),
        54 => g54(a, b),
        55 => g55(a, b),
        56 => g56(a, b),
        57 => g57(a, b),
        58 => g58(a, b),
        59 => g59(a, b),
        60 => g60(a, b),
        61 => g61(a, b),
        62 => g62(a, b),
        63 => g63(a, b),
        64 => g64(a, b),
        65 => g65(a, b),
        66 => g66(a, b),
        67 => g67(a, b),
        68 => g68(a, b),
        69 => g69(a, b),
        70 => g70(a, b),
        71 => g71(a, b),
        72 => g72(a, b),
        73 => g73(a, b),
        74 => g74(a, b),
        75 => g75(a, b),
        76 => g76(a, b),
        77 => g77(a, b),
        78 => g78(a, b),
        79 => g79(a, b),
        _ => 0,
    }
}
