// AUTO-GENERATED by gen_exprs (seed=1, count=80, depth=8, nodes=26). Do not edit.
#![allow(clippy::all, unused_parens, unused_variables, unused_mut, dead_code)]
use neo_devpack::prelude::*;
#[inline] fn gdiv(x: i64, y: i64) -> i64 { x.checked_div(y).unwrap_or(0) }
#[inline] fn grem(x: i64, y: i64) -> i64 { x.checked_rem(y).unwrap_or(0) }
#[inline] fn gdivu(x: i64, y: i64) -> i64 { if y == 0 { 0 } else { ((x as u64) / (y as u64)) as i64 } }
pub const GEN_COUNT: i64 = 80;
#[inline(never)] pub fn g0(a: i64, b: i64) -> i64 { (((((((((((-8006175397324373085i64).max(-6260278484400246991i64))) as u64) as i64)).min(b))) ^ (((((((NeoInteger::new(gdiv(a, b)) >> ((((((NeoInteger::new(((-1607326157093649467i64).min(a))) * NeoInteger::new(((4454276479544968717i64).wrapping_neg()))).as_i64_saturating())).wrapping_shl((((((5341755297032657242i64).rotate_left(((a) & 63) as u32))) ^ (a))) as u32)) & 63) as u32)).as_i64_saturating())).count_ones() as i64)).min(b))))).wrapping_abs()) }
#[inline(never)] pub fn g1(a: i64, b: i64) -> i64 { (((gdiv(a, ((NeoInteger::new(((((((b) == (((NeoInteger::new((((7578830648253265755i64) as u16) as u64 as i64)) % NeoInteger::new(((a) | 1))).as_i64_saturating()))) as i64)).wrapping_shr((((((4251471980962470017i64) ^ (b))) & (b))) as u32)) | (gdivu((((((a) < (((-6893246991004687020i64).count_ones() as i64))) as i64)).min({ let mut acc1 = (grem(1575562375169308587i64, b)); let n3 = (((a) & 7)); let mut i2 = 0i64; while i2 < n3 { acc1 = (acc1).wrapping_add((7282253600491690314i64)); i2 = i2 + 1; } acc1 })), a)))) - NeoInteger::new(b)).as_i64_saturating()))) as u32) as u64 as i64) }
#[inline(never)] pub fn g2(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g3(a: i64, b: i64) -> i64 { gdivu((((((NeoInteger::new(((b).wrapping_add((!((if (((NeoInteger::new(-3933353117309740750i64) | NeoInteger::new(b)).as_i64_saturating())) != 0 { (b).wrapping_shl((b) as u32) } else { (((32i64) as i32) as i64) }))))).wrapping_mul(b)) >> ((({ let mut acc4 = (((((((((NeoInteger::new(796103134484550370i64) >> (((-5105556534611951592i64) & 63) as u32)).as_i64_saturating())).count_ones() as i64)).wrapping_sub(2i64)) as i32) as i64)); let n6 = (((b) & 7)); let mut i5 = 0i64; while i5 < n6 { acc4 = (acc4).wrapping_add((-5886676315881575550i64)); i5 = i5 + 1; } acc4 }) & 63) as u32)).as_i64_saturating())) as u64).wrapping_shr((-1352603814869947859i64) as u32) as i64), -7686158978257740243i64) }
#[inline(never)] pub fn g4(a: i64, b: i64) -> i64 { (({ let t8 = ((((NeoInteger::new((gdiv(a, -3057082291153454823i64)).wrapping_mul(({ let t7 = (gdivu(9223372036854775807i64, 7793991512346101572i64)); ((t7).count_ones() as i64) }).wrapping_add(a))) / NeoInteger::new((((!((((((((((NeoInteger::new(b) % NeoInteger::new(((b) | 1))).as_i64_saturating())) as i32) as i64)) as u64) < (((((NeoInteger::new(64i64) - NeoInteger::new(7820102654177919510i64)).as_i64_saturating())).wrapping_shl((a) as u32)) as u64)) as i64)))) | 1))).as_i64_saturating())).wrapping_shr((63i64) as u32)); b }).rotate_left(((b) & 63) as u32)) }
#[inline(never)] pub fn g5(a: i64, b: i64) -> i64 { (((-9223372036854775808i64) as u32) as u64 as i64) }
#[inline(never)] pub fn g6(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g7(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g8(a: i64, b: i64) -> i64 { (((-7201830402704800566i64) as i32) as i64) }
#[inline(never)] pub fn g9(a: i64, b: i64) -> i64 { (((((((((((((((b) == (((((a).wrapping_mul(7938091807324906118i64)) as i32) as i64))) as i64)) as i8) as i64)) & (((((((NeoInteger::new(((b) & (a))) / NeoInteger::new(((-7710872247987188296i64) | 1))).as_i64_saturating())).wrapping_shr((((7438520504188070196i64).min(((-2147483648i64).max(b))))) as u32)) as u32) as u64 as i64)))).wrapping_neg())) as u32) as u64 as i64)).wrapping_abs()) }
#[inline(never)] pub fn g10(a: i64, b: i64) -> i64 { ((NeoInteger::new((((if (3883932740615472019i64) != 0 { b } else { ((NeoInteger::new(((NeoInteger::new(2147483648i64) % NeoInteger::new(((4314950848058761399i64) | 1))).as_i64_saturating())) % NeoInteger::new((((((b) as i8) as i64)) | 1))).as_i64_saturating()) })).min((((grem(-7731156505130217406i64, (gdiv(a, 63i64)).wrapping_mul((((((1188295635141928520i64) as i16) as i64)) ^ (b))))).wrapping_shl((((((NeoInteger::new(a) % NeoInteger::new(((-8248364952035609881i64) | 1))).as_i64_saturating())).max(a))) as u32)).count_ones() as i64)))) & NeoInteger::new(a)).as_i64_saturating()) }
#[inline(never)] pub fn g11(a: i64, b: i64) -> i64 { (b).wrapping_sub(gdivu(gdivu((((((a).wrapping_neg())).count_ones() as i64)).wrapping_shr((8250636037269548407i64) as u32), ((grem((({ let mut acc9 = (((b) & (256i64))); let n11 = (((b) & 7)); let mut i10 = 0i64; while i10 < n11 { acc9 = (acc9).wrapping_add((gdivu(7340560929042159322i64, -4966145566001142465i64))); i10 = i10 + 1; } acc9 }).wrapping_abs()), (((((a).rotate_left(((((b) | (a))) & 63) as u32))) < (-1603096601618083996i64)) as i64))).min(a))), 1907827598596822169i64)) }
#[inline(never)] pub fn g12(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g13(a: i64, b: i64) -> i64 { gdiv(((((b).wrapping_mul(((((a).wrapping_neg())) ^ ((gdivu(b, b)).wrapping_sub(((((((((b) ^ (-8884997106769059395i64))) as u64) < (((-256i64).wrapping_add(b)) as u64)) as i64)).count_ones() as i64)))))) as i32) as i64), (((a) as i8) as i64)) }
#[inline(never)] pub fn g14(a: i64, b: i64) -> i64 { ({ let t15 = ((((b) == ((((a).min(((-5917950440764139215i64) ^ ((63i64).wrapping_sub(8674928826682451374i64)))))).wrapping_mul(((8910838460081377385i64).min(((NeoInteger::new(({ let mut acc12 = (a); let n14 = (((b) & 7)); let mut i13 = 0i64; while i13 < n14 { acc12 = (acc12).wrapping_add((b)); i13 = i13 + 1; } acc12 }).wrapping_shr((grem(a, a)) as u32)) % NeoInteger::new((((((((NeoInteger::new(3722759838195805848i64) >> (((4699297447608257906i64) & 63) as u32)).as_i64_saturating())) as u64).wrapping_shr((b) as u32) as i64)) | 1))).as_i64_saturating())))))) as i64)); a }).wrapping_shr((8i64) as u32) }
#[inline(never)] pub fn g15(a: i64, b: i64) -> i64 { (((((({ let mut acc16 = (a); let n18 = ((((((((NeoInteger::new(((NeoInteger::new((((a).wrapping_mul(4611686018427387904i64)).wrapping_neg())) % NeoInteger::new(((((((a) & (b))).wrapping_abs())) | 1))).as_i64_saturating())) / NeoInteger::new(((a) | 1))).as_i64_saturating())) as i8) as i64)) & 7)); let mut i17 = 0i64; while i17 < n18 { acc16 = (acc16).wrapping_add((gdiv(((((((8123410481815909124i64) | (((NeoInteger::new(-63963437177204401i64) % NeoInteger::new(((-92721607686411676i64) | 1))).as_i64_saturating())))) ^ (a))).rotate_left(((32i64) & 63) as u32)), -8060706202698961346i64))); i17 = i17 + 1; } acc16 }) < (b)) as i64)) as i32) as i64) }
#[inline(never)] pub fn g16(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g17(a: i64, b: i64) -> i64 { (((((((((((((((((((8i64) ^ (a))) as i32) as i64)) as i8) as i64)) as u64) < ((((NeoInteger::new((((a) == (-5236731619026909498i64)) as i64)) / NeoInteger::new(((((-7696597523851513941i64) | (255i64))) | 1))).as_i64_saturating())) as u64)) as i64)).wrapping_add((((((((((a) as u64).wrapping_shr(((((b) as u32) as u64 as i64)) as u32) as i64)) | (((NeoInteger::new((a).wrapping_shr((b) as u32)) + NeoInteger::new(a)).as_i64_saturating())))) as u64) < ((b) as u64)) as i64))).wrapping_neg())) < (a)) as i64)).wrapping_add(a) }
#[inline(never)] pub fn g18(a: i64, b: i64) -> i64 { ((((a) as u64) < ((b) as u64)) as i64) }
#[inline(never)] pub fn g19(a: i64, b: i64) -> i64 { 205170249186182715i64 }
#[inline(never)] pub fn g20(a: i64, b: i64) -> i64 { ((658628110963992927i64) ^ (((-5095170078474110891i64).min(gdiv(6927825500903308804i64, 2i64))))) }
#[inline(never)] pub fn g21(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g22(a: i64, b: i64) -> i64 { 7510504456205115211i64 }
#[inline(never)] pub fn g23(a: i64, b: i64) -> i64 { ((grem(a, ((({ let mut acc19 = (a); let n21 = (((-1081492036383241757i64) & 7)); let mut i20 = 0i64; while i20 < n21 { acc19 = (acc19).wrapping_add((a)); i20 = i20 + 1; } acc19 }) as u64).wrapping_shr((((a).wrapping_neg())) as u32) as i64))).rotate_left(((((NeoInteger::new(b) + NeoInteger::new((((grem(a, (((((NeoInteger::new((if (4497465995622577722i64) != 0 { ((a).max(a)) } else { (((64i64) == (-8092756974596618653i64)) as i64) })) / NeoInteger::new(((1i64) | 1))).as_i64_saturating())) as u64).wrapping_shr((b) as u32) as i64))) < (b)) as i64))).as_i64_saturating())) & 63) as u32)) }
#[inline(never)] pub fn g24(a: i64, b: i64) -> i64 { (((a) as i32) as i64) }
#[inline(never)] pub fn g25(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g26(a: i64, b: i64) -> i64 { ((2335557196111575928i64) & ((((gdivu(((({ let t22 = (((-2147483648i64).rotate_left(((a) & 63) as u32))); (((7010055040335347810i64) as i32) as i64) }) & (((((b).wrapping_sub(a)) < (a)) as i64)))).wrapping_shr(((((a).wrapping_mul({ let mut acc23 = (-256i64); let n25 = (((2147483647i64) & 7)); let mut i24 = 0i64; while i24 < n25 { acc23 = (acc23).wrapping_add((2147483647i64)); i24 = i24 + 1; } acc23 })).count_ones() as i64)) as u32), b)).wrapping_shl((a) as u32)).wrapping_neg()))) }
#[inline(never)] pub fn g27(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g28(a: i64, b: i64) -> i64 { grem(-7093601097436182461i64, (((((b) as i8) as i64)).wrapping_neg())) }
#[inline(never)] pub fn g29(a: i64, b: i64) -> i64 { { let mut acc26 = (4788084691763931996i64); let n28 = (((gdivu(((((((b) as i8) as i64)) as i16) as i64), ((NeoInteger::new(gdivu(a, (((gdivu(((NeoInteger::new(((64i64).count_ones() as i64)) % NeoInteger::new((((((-9086252967140188426i64) < (1i64)) as i64)) | 1))).as_i64_saturating()), 4415795943143052967i64)) as i8) as i64))) / NeoInteger::new((((gdiv((((((((2147483648i64).max(1940417211586563336i64))).max(b))) as u64).wrapping_shr((b) as u32) as i64), 5937347884299589777i64)).wrapping_sub(b)) | 1))).as_i64_saturating()))) & 7)); let mut i27 = 0i64; while i27 < n28 { acc26 = (acc26).wrapping_add((acc26)); i27 = i27 + 1; } acc26 } }
#[inline(never)] pub fn g30(a: i64, b: i64) -> i64 { (((({ let t29 = (-3693918483141771842i64); ((((NeoInteger::new(((((NeoInteger::new((((7i64) == (-3267231120106399979i64)) as i64)) & NeoInteger::new(6837069237162304532i64)).as_i64_saturating())) & (63i64))) / NeoInteger::new(((((t29) | (((NeoInteger::new(((NeoInteger::new(a) / NeoInteger::new(((t29) | 1))).as_i64_saturating())) & NeoInteger::new(((NeoInteger::new(b) ^ NeoInteger::new(t29)).as_i64_saturating()))).as_i64_saturating())))) | 1))).as_i64_saturating())).min(((NeoInteger::new({ let t30 = ((((t29) as i8) as i64)); b }) % NeoInteger::new(((8527733460431666723i64) | 1))).as_i64_saturating()))) }) as u64).wrapping_shr((4294967295i64) as u32) as i64)).wrapping_shl((-2479136288672108775i64) as u32) }
#[inline(never)] pub fn g31(a: i64, b: i64) -> i64 { { let mut acc31 = (a); let n33 = ((((((((4920225401105676870i64) as u32) as u64 as i64)).min(((((((9119007907019131359i64) as u64) < ((a) as u64)) as i64)).rotate_left(((((gdivu(a, (((b) as i32) as i64))).rotate_left((((((((((b) & (256i64))).count_ones() as i64)) ^ ((((grem(6784751987340632800i64, -8921661916804838152i64)) < (((a) | (a)))) as i64)))).wrapping_mul(-4578732373006585315i64)) & 63) as u32))) & 63) as u32))))) & 7)); let mut i32 = 0i64; while i32 < n33 { acc31 = (acc31).wrapping_add((-3504538129116674582i64)); i32 = i32 + 1; } acc31 } }
#[inline(never)] pub fn g32(a: i64, b: i64) -> i64 { (((if (b) != 0 { ((NeoInteger::new(-3720464147162144538i64) >> ((((((NeoInteger::new(a) >> (((grem((((gdiv(5943417442264453885i64, b)) == ((((8i64) < (1891893694353781740i64)) as i64))) as i64), { let t34 = (((NeoInteger::new(31i64) % NeoInteger::new(((8483899434114556507i64) | 1))).as_i64_saturating())); ((7i64).wrapping_neg()) })) & 63) as u32)).as_i64_saturating())).wrapping_shl((256i64) as u32)) & 63) as u32)).as_i64_saturating()) } else { { let mut acc35 = (gdiv(a, a)); let n37 = (((961131786658205359i64) & 7)); let mut i36 = 0i64; while i36 < n37 { acc35 = (acc35).wrapping_add((acc35)); i36 = i36 + 1; } acc35 } })) ^ (534970341188817777i64)) }
#[inline(never)] pub fn g33(a: i64, b: i64) -> i64 { (((((a) as u64) < ((2i64) as u64)) as i64)).wrapping_mul(a) }
#[inline(never)] pub fn g34(a: i64, b: i64) -> i64 { ((gdivu(((((((((((if (31i64) != 0 { (-2718046863734730268i64).wrapping_sub(-9097389939596257034i64) } else { ((a).max(-6863020023490962189i64)) })).wrapping_add((if (((a).wrapping_neg())) != 0 { (a).wrapping_sub(a) } else { (if (b) != 0 { 256i64 } else { -6133133704232232024i64 }) }))) | (((8i64).rotate_left(((a) & 63) as u32))))) < (b)) as i64)) == (b)) as i64), -1i64)) | (1898295878300245275i64)) }
#[inline(never)] pub fn g35(a: i64, b: i64) -> i64 { gdivu((((((((((2147483648i64).wrapping_abs())).wrapping_shr((((((a) | ((((((4992199369917781673i64).wrapping_abs())) as u64).wrapping_shr((a) as u32) as i64)))).rotate_left(((7608811009704016765i64) & 63) as u32))) as u32)) as u32) as u64 as i64)) as i8) as i64), ((b).wrapping_abs())) }
#[inline(never)] pub fn g36(a: i64, b: i64) -> i64 { (if (4132220246161033076i64) != 0 { (((a).wrapping_shr((3061249979811515173i64) as u32)).wrapping_neg()) } else { { let t38 = (a); ((((((((((((((a).count_ones() as i64)) as u64) < (((((32i64) < (-645228118300998370i64)) as i64)) as u64)) as i64)).rotate_left(((b) & 63) as u32))) as i8) as i64)).wrapping_mul(((NeoInteger::new(((NeoInteger::new((((((a) < (8i64)) as i64)).rotate_left(((t38) & 63) as u32))) ^ NeoInteger::new(-668323767529178660i64)).as_i64_saturating())) % NeoInteger::new(((-6513990813580722113i64) | 1))).as_i64_saturating()))).wrapping_neg()) } }) }
#[inline(never)] pub fn g37(a: i64, b: i64) -> i64 { ((NeoInteger::new(((((a).wrapping_mul((!(((NeoInteger::new(((((b).rotate_left(((b) & 63) as u32))) & (((1494118602321490243i64).count_ones() as i64)))) >> ((((gdivu(b, 7918284659559154131i64)).wrapping_shr((-4952468376254024151i64) as u32)) & 63) as u32)).as_i64_saturating()))))).count_ones() as i64)).wrapping_mul((((({ let mut acc39 = (4611686018427387904i64); let n41 = (((gdiv(-4615349057962775162i64, (((((a) as i16) as i64)).count_ones() as i64))) & 7)); let mut i40 = 0i64; while i40 < n41 { acc39 = (acc39).wrapping_add((-5954076038617649401i64)); i40 = i40 + 1; } acc39 }) as u64) < ((778656409214352811i64) as u64)) as i64))) / NeoInteger::new(((b) | 1))).as_i64_saturating()) }
#[inline(never)] pub fn g38(a: i64, b: i64) -> i64 { ((((((((((((((3422173004891399593i64) | ((!(((b) & (((NeoInteger::new(b) % NeoInteger::new(((a) | 1))).as_i64_saturating())))))))).rotate_left((((((((((!(b))).wrapping_shr((((NeoInteger::new(-2112530284129565090i64) % NeoInteger::new(((a) | 1))).as_i64_saturating())) as u32)).rotate_left(((-4600986515426856709i64) & 63) as u32))) as u8) as u64 as i64)) & 63) as u32))) as u64) < ((b) as u64)) as i64)) as u32) as u64 as i64)) as u64).wrapping_shr(((((((grem(b, -4246237538358378982i64)).rotate_left(((b) & 63) as u32))) as i8) as i64)) as u32) as i64) }
#[inline(never)] pub fn g39(a: i64, b: i64) -> i64 { (!(((7554342905947341102i64).wrapping_neg()))) }
#[inline(never)] pub fn g40(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g41(a: i64, b: i64) -> i64 { ((NeoInteger::new(((-5454426120161681126i64) ^ (63i64))) >> ((((((((NeoInteger::new(((((NeoInteger::new((((((((b) & (a))) as i8) as i64)) & (b))) % NeoInteger::new((((if (((((a).wrapping_neg())).max((((256i64) == (a)) as i64)))) != 0 { ((((((NeoInteger::new(8780448364033947598i64) / NeoInteger::new(((4565715161490563426i64) | 1))).as_i64_saturating())) as u64) < ((b) as u64)) as i64) } else { b })) | 1))).as_i64_saturating())).max(-4432506685495884651i64))) + NeoInteger::new(a)).as_i64_saturating())) < (a)) as i64)) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g42(a: i64, b: i64) -> i64 { ((if ((((((((gdivu(((a) & (2982335866597611193i64)), -7905977396592470112i64)).wrapping_shl((((((a).max(-2147483648i64))).wrapping_neg())) as u32)) & (((!(((6676764338417320697i64) | (a))))).wrapping_mul(((NeoInteger::new(gdivu(8934394730282054910i64, 255i64)) % NeoInteger::new((((((-256i64) as i8) as i64)) | 1))).as_i64_saturating()))))) == (-8562101876899202194i64)) as i64)).wrapping_shr((b) as u32)) != 0 { -3383924604721728930i64 } else { a })).wrapping_shl((607790734283724956i64) as u32) }
#[inline(never)] pub fn g43(a: i64, b: i64) -> i64 { gdivu(((((((((NeoInteger::new(((-6665774542344357398i64).count_ones() as i64)) ^ NeoInteger::new(-9213216951601685848i64)).as_i64_saturating())) as u32) as u64 as i64)) as u16) as u64 as i64), (a).wrapping_sub(9223372036854775807i64)) }
#[inline(never)] pub fn g44(a: i64, b: i64) -> i64 { ((((a) as u64) < ((a) as u64)) as i64) }
#[inline(never)] pub fn g45(a: i64, b: i64) -> i64 { (((((((((((((((a) as u32) as u64 as i64)).wrapping_neg())).rotate_left(((31i64) & 63) as u32))).wrapping_add(1i64)).rotate_left(((((((((((((-5853594465759305004i64) as u64).wrapping_shr((8i64) as u32) as i64)) as i32) as i64)).wrapping_shr(((((((b) ^ (b))) as i8) as i64)) as u32)) as i8) as i64)) & 63) as u32))).wrapping_abs())).wrapping_shl((((a).wrapping_abs())) as u32)) & ((((((9162027635100100735i64) < (-7114149556243242748i64)) as i64)).min(b)))) }
#[inline(never)] pub fn g46(a: i64, b: i64) -> i64 { { let t45 = ((((NeoInteger::new(7480001143133081637i64) - NeoInteger::new(((((gdivu((((gdivu((b).wrapping_shr((b) as u32), ((-8021876633803821253i64).wrapping_abs()))) as i8) as i64), gdivu((6058733104890721702i64).wrapping_mul((((a) as i8) as i64)), ((NeoInteger::new({ let mut acc42 = (7787161148022770317i64); let n44 = (((a) & 7)); let mut i43 = 0i64; while i43 < n44 { acc42 = (acc42).wrapping_add((4751077093278912831i64)); i43 = i43 + 1; } acc42 }) & NeoInteger::new(((0i64).min(b)))).as_i64_saturating())))) as u64) < ((31i64) as u64)) as i64))).as_i64_saturating())).wrapping_sub(2i64)); 31i64 } }
#[inline(never)] pub fn g47(a: i64, b: i64) -> i64 { (((grem((((((((((({ let t46 = ((((-6005587143129247478i64) as i16) as i64)); t46 }).wrapping_add((((if (b) != 0 { a } else { b })).max(((NeoInteger::new(1i64) / NeoInteger::new(((-2147483648i64) | 1))).as_i64_saturating()))))) as u64) < (((((gdivu(((NeoInteger::new(a) >> (((a) & 63) as u32)).as_i64_saturating()), ((NeoInteger::new(b) % NeoInteger::new(((b) | 1))).as_i64_saturating()))) as u32) as u64 as i64)) as u64)) as i64)).wrapping_abs())) == (-8172490770644331309i64)) as i64), a)) as i32) as i64) }
#[inline(never)] pub fn g48(a: i64, b: i64) -> i64 { (((a) as i8) as i64) }
#[inline(never)] pub fn g49(a: i64, b: i64) -> i64 { ((NeoInteger::new((((gdiv(grem(b, ((8i64).rotate_left((({ let t47 = (8377595309657733757i64); ((NeoInteger::new(((NeoInteger::new(4294967295i64) >> (((-1673222151907050680i64) & 63) as u32)).as_i64_saturating())) * NeoInteger::new(gdiv(a, b))).as_i64_saturating()) }) & 63) as u32))), b)) as u32) as u64 as i64)) >> (((((((NeoInteger::new(a) - NeoInteger::new(gdiv(gdivu((((((b) & (-1118721823969934709i64))) as u8) as u64 as i64), a), a))).as_i64_saturating())) | (-8418416388552741403i64))) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g50(a: i64, b: i64) -> i64 { ((NeoInteger::new(((((NeoInteger::new((if (-1i64) != 0 { ((((((NeoInteger::new((b).wrapping_shr((b) as u32)) / NeoInteger::new(((gdivu(a, b)) | 1))).as_i64_saturating())).wrapping_neg())).max(((gdiv(((b).count_ones() as i64), b)).min(((NeoInteger::new((a).wrapping_add(b)) * NeoInteger::new((a).wrapping_shr((b) as u32))).as_i64_saturating()))))) } else { b })) >> (((-8782766219450955504i64) & 63) as u32)).as_i64_saturating())).min(b))) >> (((-565343867571818578i64) & 63) as u32)).as_i64_saturating()) }
#[inline(never)] pub fn g51(a: i64, b: i64) -> i64 { ((b).count_ones() as i64) }
#[inline(never)] pub fn g52(a: i64, b: i64) -> i64 { { let mut acc48 = (a); let n50 = (((((gdivu(-486426240853436176i64, ((((NeoInteger::new(b) * NeoInteger::new(b)).as_i64_saturating())).wrapping_abs()))).min(((NeoInteger::new(b) + NeoInteger::new((((((((if (b) != 0 { -1140244859446725212i64 } else { 2i64 })) & (gdiv(b, a)))) | ((((a).count_ones() as i64)).wrapping_add(8131440680921331950i64)))).wrapping_shl((2809785134364953427i64) as u32)).wrapping_sub(-1769421300938537130i64))).as_i64_saturating())))) & 7)); let mut i49 = 0i64; while i49 < n50 { acc48 = (acc48).wrapping_add((a)); i49 = i49 + 1; } acc48 } }
#[inline(never)] pub fn g53(a: i64, b: i64) -> i64 { (((-5802533807891579402i64) as u16) as u64 as i64) }
#[inline(never)] pub fn g54(a: i64, b: i64) -> i64 { -2407551602619467757i64 }
#[inline(never)] pub fn g55(a: i64, b: i64) -> i64 { ((NeoInteger::new(((b).wrapping_neg())) % NeoInteger::new(((-7006033413867522187i64) | 1))).as_i64_saturating()) }
#[inline(never)] pub fn g56(a: i64, b: i64) -> i64 { gdiv(((((if ({ let mut acc58 = (((((((((-5165924560932005314i64) as u32) as u64 as i64)).rotate_left((({ let mut acc51 = (-7735618402969974823i64); let n53 = (((b) & 7)); let mut i52 = 0i64; while i52 < n53 { acc51 = (acc51).wrapping_add((b)); i52 = i52 + 1; } acc51 }) & 63) as u32))).wrapping_sub({ let mut acc54 = (1430197576095009819i64); let n56 = (((((NeoInteger::new(2088373377366843111i64) / NeoInteger::new(((b) | 1))).as_i64_saturating())) & 7)); let mut i55 = 0i64; while i55 < n56 { acc54 = (acc54).wrapping_add((((7101262881966250931i64) & (b)))); i55 = i55 + 1; } acc54 })) & ({ let t57 = ((((1i64) < ((7224835995075943998i64).wrapping_sub(b))) as i64)); 32i64 }))); let n60 = (((-1628750221333199354i64) & 7)); let mut i59 = 0i64; while i59 < n60 { acc58 = (acc58).wrapping_add((a)); i59 = i59 + 1; } acc58 }) != 0 { a } else { b })) as i8) as i64), b) }
#[inline(never)] pub fn g57(a: i64, b: i64) -> i64 { (((NeoInteger::new((!(((((((6482224376251441292i64) < (((((NeoInteger::new(b) % NeoInteger::new(((a) | 1))).as_i64_saturating())).min((((b) < (32i64)) as i64))))) as i64)).wrapping_mul(((((((a).max(((NeoInteger::new(b) / NeoInteger::new(((8i64) | 1))).as_i64_saturating())))) as u64) < ((((((((4294967295i64) as u64).wrapping_shr((b) as u32) as i64)) as u64).wrapping_shr(((((b) < (-1276675326821693005i64)) as i64)) as u32) as i64)) as u64)) as i64))).min(a))))) >> (((a) & 63) as u32)).as_i64_saturating())).wrapping_shl((1033270298680735699i64) as u32) }
#[inline(never)] pub fn g58(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g59(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g60(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g61(a: i64, b: i64) -> i64 { ((NeoInteger::new((!((((((((!(b))) ^ (((((((({ let mut acc61 = (b); let n63 = (((a) & 7)); let mut i62 = 0i64; while i62 < n63 { acc61 = (acc61).wrapping_add((-1522464276139823630i64)); i62 = i62 + 1; } acc61 }) as i32) as i64)).wrapping_neg())) | (((NeoInteger::new(63i64) | NeoInteger::new((((((((256i64) as u64) < ((a) as u64)) as i64)) as u32) as u64 as i64))).as_i64_saturating())))))) as u64) < (((!((((((8923833959818952205i64).wrapping_add(grem(-3496390542636664653i64, a))) as u64) < ((a) as u64)) as i64)))) as u64)) as i64)))) % NeoInteger::new(((290463314250713338i64) | 1))).as_i64_saturating()) }
#[inline(never)] pub fn g62(a: i64, b: i64) -> i64 { (((((if (a) != 0 { (((((((NeoInteger::new(-2147483648i64) % NeoInteger::new(((b) | 1))).as_i64_saturating())).min(((((a) == ((!(a)))) as i64)).wrapping_mul(b)))) as u32) as u64 as i64) } else { { let mut acc67 = ((((({ let mut acc64 = ((((8i64) as u64).wrapping_shr((9221594859585653100i64) as u32) as i64)); let n66 = (((((NeoInteger::new(a) / NeoInteger::new(((1i64) | 1))).as_i64_saturating())) & 7)); let mut i65 = 0i64; while i65 < n66 { acc64 = (acc64).wrapping_add((3665727549115862592i64)); i65 = i65 + 1; } acc64 }).rotate_left(((a) & 63) as u32))) ^ (-6982531799231975836i64))); let n69 = (((a) & 7)); let mut i68 = 0i64; while i68 < n69 { acc67 = (acc67).wrapping_add((1848632668005380346i64)); i68 = i68 + 1; } acc67 } })) & (0i64))).count_ones() as i64) }
#[inline(never)] pub fn g63(a: i64, b: i64) -> i64 { (((({ let t70 = (((7771598348174530534i64).rotate_left(((((a).wrapping_abs())) & 63) as u32))); (({ let mut acc71 = ((((grem(((NeoInteger::new(-5818190056598604183i64) / NeoInteger::new(((-1226107683511759773i64) | 1))).as_i64_saturating()), ((a).min(b)))) as i8) as i64)); let n73 = ((((2147483647i64).wrapping_add((((((t70) as u16) as u64 as i64)).min(gdiv(0i64, b))))) & 7)); let mut i72 = 0i64; while i72 < n73 { acc71 = (acc71).wrapping_add((a)); i72 = i72 + 1; } acc71 }) | (-693872345608931684i64)) }) ^ (8i64))) ^ (2i64)) }
#[inline(never)] pub fn g64(a: i64, b: i64) -> i64 { (((((((((b) as u16) as u64 as i64)) as u64) < ((((((((((((({ let t74 = (-9223372036854775808i64); b }).wrapping_abs())).max(a))).wrapping_shr((((((((2800454490143554320i64) as u32) as u64 as i64)).wrapping_sub(((b).wrapping_neg()))).wrapping_neg())) as u32)).rotate_left(((((NeoInteger::new(b) / NeoInteger::new((((((({ let t75 = (a); { let mut acc76 = (8118860713829359145i64); let n78 = (((-5183497508505607415i64) & 7)); let mut i77 = 0i64; while i77 < n78 { acc76 = (acc76).wrapping_add((255i64)); i77 = i77 + 1; } acc76 } }) as u64) < ((7i64) as u64)) as i64)) | 1))).as_i64_saturating())) & 63) as u32))) as u64) < ((a) as u64)) as i64)) as u64)) as i64)).count_ones() as i64) }
#[inline(never)] pub fn g65(a: i64, b: i64) -> i64 { ((((((-2449207363459540238i64).wrapping_shr((((NeoInteger::new((!((((7i64) == (((b).wrapping_mul(4315618222997146569i64)).wrapping_mul(gdiv(-1289848810833820716i64, -3989307548297806880i64)))) as i64)))) & NeoInteger::new((((a) < (((-2246765340672145090i64).max(b)))) as i64))).as_i64_saturating())) as u32)) | ((({ let t79 = ((((a) < (((32i64) & (a)))) as i64)); 3946403586275112307i64 }).wrapping_abs())))) as u16) as u64 as i64) }
#[inline(never)] pub fn g66(a: i64, b: i64) -> i64 { ((({ let t80 = (31i64); (if (((((NeoInteger::new(((((((((t80) as u32) as u64 as i64)).wrapping_neg())) as i32) as i64)) >> ((({ let t81 = ((((4642859581403917371i64) | (-8069881130375724766i64))).wrapping_sub(a)); t80 }) & 63) as u32)).as_i64_saturating())).count_ones() as i64)) != 0 { (((b) as u8) as u64 as i64) } else { t80 }) }) as u64) as i64) }
#[inline(never)] pub fn g67(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g68(a: i64, b: i64) -> i64 { (if (a) != 0 { grem(((gdivu(-6967449404968350804i64, (if ((((((((a).count_ones() as i64)) as u16) as u64 as i64)).count_ones() as i64)) != 0 { b } else { ((NeoInteger::new(a) ^ NeoInteger::new(((((a).max(a))) ^ ((((a) as u16) as u64 as i64))))).as_i64_saturating()) }))).min({ let mut acc82 = (((4438434928454216400i64).rotate_left(((gdivu(-4160056224157335124i64, 6609509580828328336i64)) & 63) as u32))); let n84 = (((63i64) & 7)); let mut i83 = 0i64; while i83 < n84 { acc82 = (acc82).wrapping_add((a)); i83 = i83 + 1; } acc82 })), a) } else { 9090716535204860069i64 }) }
#[inline(never)] pub fn g69(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g70(a: i64, b: i64) -> i64 { 2141055484871878731i64 }
#[inline(never)] pub fn g71(a: i64, b: i64) -> i64 { grem(-9223372036854775808i64, 5991220950792124432i64) }
#[inline(never)] pub fn g72(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g73(a: i64, b: i64) -> i64 { (if (-2147483648i64) != 0 { ((NeoInteger::new(((((((255i64) as i8) as i64)) as i8) as i64)) / NeoInteger::new(((gdiv(((NeoInteger::new({ let t85 = ((((((((-7520359699697099955i64) as u64) as i64)) as i8) as i64)).wrapping_shr(((((-5034616315111271i64).wrapping_shl((b) as u32)) | (((2147483648i64).max(2147483648i64))))) as u32)); ((((((!(b))) as u64).wrapping_shr((((64i64) | (-8790602955007176224i64))) as u32) as i64)) ^ (1627504150364356896i64)) }) / NeoInteger::new(((a) | 1))).as_i64_saturating()), 5918965566650202706i64)) | 1))).as_i64_saturating()) } else { b }) }
#[inline(never)] pub fn g74(a: i64, b: i64) -> i64 { { let t89 = ((!(((((NeoInteger::new((({ let mut acc86 = ((!(gdivu(-9062285382887662653i64, a)))); let n88 = ((((((2147483648i64).count_ones() as i64)).wrapping_sub(((0i64) & (b)))) & 7)); let mut i87 = 0i64; while i87 < n88 { acc86 = (acc86).wrapping_add(((if ((b).wrapping_mul(2i64)) != 0 { ((acc86).wrapping_neg()) } else { (((-8912452239503242776i64) == (8061218952879895468i64)) as i64) }))); i87 = i87 + 1; } acc86 }).min(5263063313563774238i64))) | NeoInteger::new(b)).as_i64_saturating())) & (-6416583267586471104i64))))); b } }
#[inline(never)] pub fn g75(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g76(a: i64, b: i64) -> i64 { 5242339604354865987i64 }
#[inline(never)] pub fn g77(a: i64, b: i64) -> i64 { (((((NeoInteger::new(gdiv(-100002351245681948i64, (((((((((((646691101433389354i64).wrapping_neg())) | (b))) as u64).wrapping_shr((((NeoInteger::new(a) % NeoInteger::new((((((-2427336696856769844i64) == (-6651538937605328567i64)) as i64)) | 1))).as_i64_saturating())) as u32) as i64)).wrapping_neg())).wrapping_abs()))) / NeoInteger::new(((((((!(a))) as i8) as i64)) | 1))).as_i64_saturating())) < (((255i64).max(((NeoInteger::new(4832270403628812083i64) & NeoInteger::new(((((4398634894336772224i64).wrapping_neg())).rotate_left(((9223372036854775807i64) & 63) as u32)))).as_i64_saturating()))))) as i64) }
#[inline(never)] pub fn g78(a: i64, b: i64) -> i64 { (((gdivu(((((-256i64) as i32) as i64)).wrapping_shl((((NeoInteger::new((b).wrapping_mul(b)) / NeoInteger::new(((((((((((a) as i8) as i64)) | (((-2393362313055079567i64) | (31i64))))) == (a)) as i64)) | 1))).as_i64_saturating())) as u32), (((2918762892882936086i64) as i16) as i64))) & ((((((NeoInteger::new(((((b).wrapping_sub(a)).wrapping_neg())).wrapping_mul(64i64)) >> (((255i64) & 63) as u32)).as_i64_saturating())) == (8495190726053457707i64)) as i64)))).wrapping_mul(-7771436086363298434i64) }
#[inline(never)] pub fn g79(a: i64, b: i64) -> i64 { a }
pub fn eval_idx(idx: i64, a: i64, b: i64) -> i64 {
    match idx {
        0 => g0(a, b),
        1 => g1(a, b),
        2 => g2(a, b),
        3 => g3(a, b),
        4 => g4(a, b),
        5 => g5(a, b),
        6 => g6(a, b),
        7 => g7(a, b),
        8 => g8(a, b),
        9 => g9(a, b),
        10 => g10(a, b),
        11 => g11(a, b),
        12 => g12(a, b),
        13 => g13(a, b),
        14 => g14(a, b),
        15 => g15(a, b),
        16 => g16(a, b),
        17 => g17(a, b),
        18 => g18(a, b),
        19 => g19(a, b),
        20 => g20(a, b),
        21 => g21(a, b),
        22 => g22(a, b),
        23 => g23(a, b),
        24 => g24(a, b),
        25 => g25(a, b),
        26 => g26(a, b),
        27 => g27(a, b),
        28 => g28(a, b),
        29 => g29(a, b),
        30 => g30(a, b),
        31 => g31(a, b),
        32 => g32(a, b),
        33 => g33(a, b),
        34 => g34(a, b),
        35 => g35(a, b),
        36 => g36(a, b),
        37 => g37(a, b),
        38 => g38(a, b),
        39 => g39(a, b),
        40 => g40(a, b),
        41 => g41(a, b),
        42 => g42(a, b),
        43 => g43(a, b),
        44 => g44(a, b),
        45 => g45(a, b),
        46 => g46(a, b),
        47 => g47(a, b),
        48 => g48(a, b),
        49 => g49(a, b),
        50 => g50(a, b),
        51 => g51(a, b),
        52 => g52(a, b),
        53 => g53(a, b),
        54 => g54(a, b),
        55 => g55(a, b),
        56 => g56(a, b),
        57 => g57(a, b),
        58 => g58(a, b),
        59 => g59(a, b),
        60 => g60(a, b),
        61 => g61(a, b),
        62 => g62(a, b),
        63 => g63(a, b),
        64 => g64(a, b),
        65 => g65(a, b),
        66 => g66(a, b),
        67 => g67(a, b),
        68 => g68(a, b),
        69 => g69(a, b),
        70 => g70(a, b),
        71 => g71(a, b),
        72 => g72(a, b),
        73 => g73(a, b),
        74 => g74(a, b),
        75 => g75(a, b),
        76 => g76(a, b),
        77 => g77(a, b),
        78 => g78(a, b),
        79 => g79(a, b),
        _ => 0,
    }
}
