// AUTO-GENERATED by gen_exprs (seed=1, count=48, depth=8, nodes=20). Do not edit.
#![allow(clippy::all, unused_parens, unused_variables, unused_mut, dead_code)]
use neo_devpack::prelude::*;
#[inline] fn gdiv(x: i64, y: i64) -> i64 { x.checked_div(y).unwrap_or(0) }
#[inline] fn grem(x: i64, y: i64) -> i64 { x.checked_rem(y).unwrap_or(0) }
#[inline] fn gdivu(x: i64, y: i64) -> i64 { if y == 0 { 0 } else { ((x as u64) / (y as u64)) as i64 } }
pub const GEN_COUNT: i64 = 48;
#[inline(never)] pub fn g0(a: i64, b: i64) -> i64 { ((NeoInteger::new(({ let arr: [i64; 4] = [(((((-8006175397324373085i64) as u64) < ((-6260278484400246991i64) as u64)) as i64)).wrapping_add(gdiv(7244712798012994009i64, (((((NeoInteger::new((((a) < (a)) as i64)) >> (((((a).count_ones() as i64)) & 63) as u32)).as_i64_saturating())) as i32) as i64))), ((!NeoInteger::new((grem(9223372036854775807i64, b)).wrapping_sub(b))).as_i64_saturating()), b, 7387658765462785795i64]; arr[(((2i64) & 3) as usize)] }).wrapping_mul(a)) % NeoInteger::new(((a) | 1))).as_i64_saturating()) }
#[inline(never)] pub fn g1(a: i64, b: i64) -> i64 { ((NeoInteger::new((((((NeoInteger::new((b).wrapping_shl((((NeoInteger::new((((gdiv((b).wrapping_mul(-6550085422901918182i64), ((4294967295i64).wrapping_abs()))) < (a)) as i64)) | NeoInteger::new(b)).as_i64_saturating())) as u32)) + NeoInteger::new(((((7i64) | ({ let arr: [i64; 4] = [b, a, 31i64, b]; arr[(((7170865108710710638i64) & 3) as usize)] }))).wrapping_abs()))).as_i64_saturating())) == (a)) as i64)) % NeoInteger::new(((b) | 1))).as_i64_saturating()) }
#[inline(never)] pub fn g2(a: i64, b: i64) -> i64 { ((8804583508467092202i64).wrapping_shl((gdivu((((-8986946105997283349i64) as u32) as u64 as i64), b)) as u32)).wrapping_shr(((((((((((((((((b) as i32).rotate_right(((((((((5648223188748024363i64).min(0i64))) as u32).wrapping_shr((8834816474567457570i64) as u32) as i32) as i64)) & 31) as u32)) as i64)) as u32) as u64 as i64)).wrapping_neg())) as u64) < ((-8003857789572763269i64) as u64)) as i64)) ^ (-9223372036854775808i64))) as u32) }
#[inline(never)] pub fn g3(a: i64, b: i64) -> i64 { (b).wrapping_mul({ let mut acc2 = ((((((((((((((((a) ^ (b))) as i8) as i64)) as i32).rotate_right(((((!NeoInteger::new(((-5886676315881575550i64) ^ (-1352603814869947859i64)))).as_i64_saturating())) & 31) as u32)) as i64)).wrapping_shl(({ let t1 = ((((b).count_ones() as i64)).wrapping_shl((b) as u32)); b }) as u32)) == (a)) as i64)).wrapping_neg())); let n4 = (((a) & 7)); let mut i3 = 0i64; while i3 < n4 { acc2 = (acc2).wrapping_add((b)); i3 = i3 + 1; } acc2 }) }
#[inline(never)] pub fn g4(a: i64, b: i64) -> i64 { -3057082291153454823i64 }
#[inline(never)] pub fn g5(a: i64, b: i64) -> i64 { ((((((((((((((((((((((((a) as u64) < ((b) as u64)) as i64)) < (((b).count_ones() as i64))) as i64)) == ((((((-7480087157118483103i64) as u64).wrapping_shr((2i64) as u32) as i64)).rotate_left((((8i64).wrapping_sub(7820102654177919510i64)) & 63) as u32)))) as i64)) as u64) < ((a) as u64)) as i64)).wrapping_shl((63i64) as u32)) ^ (a))) as i8) as i64)) as i32).rotate_right(((b) & 31) as u32)) as i64) }
#[inline(never)] pub fn g6(a: i64, b: i64) -> i64 { (((-9223372036854775808i64) as u32) as u64 as i64) }
#[inline(never)] pub fn g7(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g8(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g9(a: i64, b: i64) -> i64 { gdiv(-7201830402704800566i64, (({ let ma: [i64; 4] = [(((((((NeoInteger::new(grem(b, ((NeoInteger::new(b) >> (((a) & 63) as u32)).as_i64_saturating()))) / NeoInteger::new(((((((7i64) as u32) as u64 as i64)).wrapping_shr((((255i64) | (-1i64))) as u32)) | 1))).as_i64_saturating())) as i16) as i64)).count_ones() as i64), ((b).wrapping_abs()), -2275712521371942093i64, -1i64]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }) ^ (-8115338347961466670i64))) }
#[inline(never)] pub fn g10(a: i64, b: i64) -> i64 { gdiv((((((if (((((((((((({ let ma: [i64; 4] = [b, -1114069476582516548i64, 2147483648i64, b]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }) as i8) as i64)) as i8) as i64)) as u64) < (((((((b).wrapping_sub(gdiv(-2147483648i64, a))) as u32).wrapping_shr(({ let t5 = (a); b }) as u32) as i32) as i64)) as u64)) as i64)) < (9060806177018537762i64)) { (a) } else { (63i64) })).wrapping_shl((-2184011611607278397i64) as u32)) == (b)) as i64), 2649755346086208516i64) }
#[inline(never)] pub fn g11(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g12(a: i64, b: i64) -> i64 { ((((NeoInteger::new(b) % NeoInteger::new(((-2650285457101728866i64) | 1))).as_i64_saturating())).wrapping_abs()) }
#[inline(never)] pub fn g13(a: i64, b: i64) -> i64 { gdivu(4170096225751424852i64, (({ let mut acc6 = (((!NeoInteger::new((if ((((((a) & (8250636037269548407i64))) as u16) as u64 as i64)) != 0 { (((((((NeoInteger::new(a) / NeoInteger::new(((32i64) | 1))).as_i64_saturating())).max(((-7241652019600198476i64).wrapping_neg())))) as i8) as i64) } else { (((((a) as u32) as u64 as i64)) | (-4966145566001142465i64)) }))).as_i64_saturating())); let n8 = (((31i64) & 7)); let mut i7 = 0i64; while i7 < n8 { acc6 = (acc6).wrapping_add((-8400946649103168498i64)); i7 = i7 + 1; } acc6 }).min(b))) }
#[inline(never)] pub fn g14(a: i64, b: i64) -> i64 { (((((((!NeoInteger::new(((({ let mut acc9 = (((((((NeoInteger::new(4294967295i64) / NeoInteger::new(((b) | 1))).as_i64_saturating())).wrapping_shr((a) as u32)) == ((if (((((-5040673305794198976i64) as i8) as i64)) < (5374506159366941815i64)) { ({ let arr: [i64; 4] = [b, a, 0i64, 6012361656121139987i64]; arr[(((-6613359419640277903i64) & 3) as usize)] }) } else { (-8884997106769059395i64) }))) as i64)); let n11 = (((b) & 7)); let mut i10 = 0i64; while i10 < n11 { acc9 = (acc9).wrapping_add((-256i64)); i10 = i10 + 1; } acc9 }) as i32) as i64))).as_i64_saturating())).wrapping_neg())) as i8) as i64) }
#[inline(never)] pub fn g15(a: i64, b: i64) -> i64 { 4611686018427387904i64 }
#[inline(never)] pub fn g16(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g17(a: i64, b: i64) -> i64 { (if (grem(((b).min(((((((a) | (((-5917950440764139215i64).wrapping_abs())))) as u64) < (((if (63i64) != 0 { 8674928826682451374i64 } else { ((8910838460081377385i64) | ((({ let arr: [i64; 4] = [b, a, b, b]; arr[(((6003810161411164236i64) & 3) as usize)] }) ^ (a)))) })) as u64)) as i64))), b)) != 0 { -2860290331057958293i64 } else { 3722759838195805848i64 }) }
#[inline(never)] pub fn g18(a: i64, b: i64) -> i64 { { let arr: [i64; 4] = [(((((if ({ let mut acc12 = (((NeoInteger::new((((((NeoInteger::new(a) | NeoInteger::new(3209703939222341250i64)).as_i64_saturating())) as i32) as i64)) >> ((((if (((((b) as u64).wrapping_shr((2147483647i64) as u32) as i64)) < (((NeoInteger::new(7i64) >> (((-256i64) & 63) as u32)).as_i64_saturating()))) { (b) } else { (a) })) & 63) as u32)).as_i64_saturating())); let n14 = (((-9223372036854775808i64) & 7)); let mut i13 = 0i64; while i13 < n14 { acc12 = (acc12).wrapping_add((a)); i13 = i13 + 1; } acc12 }) != 0 { b } else { -1915283307873192909i64 })) | (-1997668400450464030i64))).count_ones() as i64), -256i64, -3213795455146408086i64, a]; arr[(((a) & 3) as usize)] } }
#[inline(never)] pub fn g19(a: i64, b: i64) -> i64 { (((((((gdiv(b, ((NeoInteger::new((((((((NeoInteger::new(8414721639893303982i64) >> (((7092399794215597014i64) & 63) as u32)).as_i64_saturating())) as u16) as u64 as i64)).wrapping_neg())) >> ((({ let arr: [i64; 4] = [(((a) == ((((-256i64) as i32) as i64))) as i64), b, b, b]; arr[(((b) & 3) as usize)] }) & 63) as u32)).as_i64_saturating()))).max(b))) < (a)) as i64)).rotate_left(((-6572820121507194770i64) & 63) as u32)) }
#[inline(never)] pub fn g20(a: i64, b: i64) -> i64 { (((({ let arr: [i64; 4] = [(((-5848153505398414310i64) as u32) as u64 as i64), grem((((a).count_ones() as i64)).wrapping_shl((1764840108231200768i64) as u32), b), a, a]; arr[((((({ let ma: [i64; 4] = [((NeoInteger::new(b) >> ((((((grem(b, b)) as u16) as u64 as i64)) & 63) as u32)).as_i64_saturating()), a, 6927825500903308804i64, b]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }).count_ones() as i64)) & 3) as usize)] }).wrapping_abs())).wrapping_neg()) }
#[inline(never)] pub fn g21(a: i64, b: i64) -> i64 { (((a) as i32) as i64) }
#[inline(never)] pub fn g22(a: i64, b: i64) -> i64 { 7510504456205115211i64 }
#[inline(never)] pub fn g23(a: i64, b: i64) -> i64 { (((a).wrapping_sub({ let mut acc15 = (((NeoInteger::new(a) % NeoInteger::new(((-1081492036383241757i64) | 1))).as_i64_saturating())); let n17 = (((b) & 7)); let mut i16 = 0i64; while i16 < n17 { acc15 = (acc15).wrapping_add(((a).wrapping_add((((b) as u32) as u64 as i64)))); i16 = i16 + 1; } acc15 })).count_ones() as i64) }
#[inline(never)] pub fn g24(a: i64, b: i64) -> i64 { 1i64 }
#[inline(never)] pub fn g25(a: i64, b: i64) -> i64 { ((b) | (grem(((((((((((((a) ^ (((64i64).min(-8092756974596618653i64))))) as i32) as i64)) ^ (((({ let t18 = (((((0i64) as u32).wrapping_shr((a) as u32) as i32) as i64)); ((t18) | (0i64)) }) < (2335557196111575928i64)) as i64)))).rotate_left(((b) & 63) as u32))) == (-9223372036854775808i64)) as i64), b))) }
#[inline(never)] pub fn g26(a: i64, b: i64) -> i64 { 4611686018427387904i64 }
#[inline(never)] pub fn g27(a: i64, b: i64) -> i64 { ((((({ let ma: [i64; 4] = [((gdivu(((((((1i64).min(a))) as u64) < ((a) as u64)) as i64), ((((((!NeoInteger::new(a)).as_i64_saturating())) as i32).rotate_right(((6427888367715055281i64) & 31) as u32)) as i64))).wrapping_add(b)).wrapping_mul(((b).wrapping_add(a)).wrapping_add(a)), 2369378832038359519i64, b, b]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }) as i8) as i64)) | (256i64)) }
#[inline(never)] pub fn g28(a: i64, b: i64) -> i64 { (((-9175907002909345958i64) as u64).wrapping_shr((4788084691763931996i64) as u32) as i64) }
#[inline(never)] pub fn g29(a: i64, b: i64) -> i64 { ((((((((b) | (a))).count_ones() as i64)) as u64) < ((((a).wrapping_abs())) as u64)) as i64) }
#[inline(never)] pub fn g30(a: i64, b: i64) -> i64 { { let t19 = (((NeoInteger::new(((NeoInteger::new(((if (((!((((((NeoInteger::new(1i64) >> (((b) & 63) as u32)).as_i64_saturating())) as i32) as i64)))) < (0i64)) { (((((((NeoInteger::new(((NeoInteger::new(3307404129133002947i64) + NeoInteger::new(b)).as_i64_saturating())) % NeoInteger::new(((a) | 1))).as_i64_saturating())) as i32).rotate_right((((((((8111328584132668640i64) as u64).wrapping_shr((-6243631937608264784i64) as u32) as i64)).wrapping_neg())) & 31) as u32)) as i64)) } else { (2147483648i64) })).wrapping_add(a)) % NeoInteger::new(((a) | 1))).as_i64_saturating())) % NeoInteger::new(((-3693918483141771842i64) | 1))).as_i64_saturating())); 952609655438890627i64 } }
#[inline(never)] pub fn g31(a: i64, b: i64) -> i64 { ((NeoInteger::new(((NeoInteger::new((((((if ((b) < (((NeoInteger::new(((!NeoInteger::new(((NeoInteger::new(b) & NeoInteger::new(a)).as_i64_saturating()))).as_i64_saturating())) % NeoInteger::new(((b) | 1))).as_i64_saturating()))) { (((NeoInteger::new((((((((b) < (((NeoInteger::new(b) % NeoInteger::new(((-9173675836502288693i64) | 1))).as_i64_saturating()))) as i64)) as u32).wrapping_shr(((a).wrapping_mul(6713013803079321106i64)) as u32) as i32) as i64)) * NeoInteger::new(b)).as_i64_saturating())) } else { (8527733460431666723i64) })) as u32).wrapping_shr((4294967295i64) as u32) as i32) as i64)) % NeoInteger::new(((-2479136288672108775i64) | 1))).as_i64_saturating())) - NeoInteger::new(4160407576794253836i64)).as_i64_saturating()) }
#[inline(never)] pub fn g32(a: i64, b: i64) -> i64 { -8726758567815513850i64 }
#[inline(never)] pub fn g33(a: i64, b: i64) -> i64 { b }
#[inline(never)] pub fn g34(a: i64, b: i64) -> i64 { (((((NeoInteger::new(9119007907019131359i64) % NeoInteger::new(((a) | 1))).as_i64_saturating())).rotate_left(((((NeoInteger::new(((((a) as u64) < (((((b) as i32) as i64)) as u64)) as i64)) >> (((((NeoInteger::new({ let ma: [i64; 4] = [(if (((((256i64).count_ones() as i64)).wrapping_add(((NeoInteger::new(b) >> (((6784751987340632800i64) & 63) as u32)).as_i64_saturating()))) < (-8921661916804838152i64)) { (-7439873843114089950i64) } else { (a) }), b, b, -3504538129116674582i64]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }) % NeoInteger::new(((-4296999969500471447i64) | 1))).as_i64_saturating())) & 63) as u32)).as_i64_saturating())) & 63) as u32))).wrapping_add(-6803747218427141982i64) }
#[inline(never)] pub fn g35(a: i64, b: i64) -> i64 { (((((((NeoInteger::new((((((NeoInteger::new((b).wrapping_shr(({ let arr: [i64; 4] = [-2147483648i64, (!(b)), (if ((8i64) < (1891893694353781740i64)) { (5852103300800220797i64) } else { (4131738195177621147i64) }), (((b) == (4611686018427387904i64)) as i64)]; arr[(((2254864843587750552i64) & 3) as usize)] }) as u32)) >> (((256i64) & 63) as u32)).as_i64_saturating())) as i8) as i64)) / NeoInteger::new(((4728662844184715014i64) | 1))).as_i64_saturating())) as u64) < ((a) as u64)) as i64)).wrapping_shl((a) as u32) }
#[inline(never)] pub fn g36(a: i64, b: i64) -> i64 { (((NeoInteger::new(((NeoInteger::new((((((((!(a))) as u64).wrapping_shr((((((((a) & (b))) as i32).rotate_right((({ let mut acc20 = (3302649137073686622i64); let n22 = (((b) & 7)); let mut i21 = 0i64; while i21 < n22 { acc20 = (acc20).wrapping_add((b)); i21 = i21 + 1; } acc20 }) & 31) as u32)) as i64)) as u32) as i64)).wrapping_add(2195285952632350708i64)) | ((if (((!(-4726465293617206736i64))) < (b)) { (a) } else { (-3866474427917781702i64) })))) + NeoInteger::new(-6863020023490962189i64)).as_i64_saturating())) / NeoInteger::new(((a) | 1))).as_i64_saturating())).wrapping_sub(0i64) }
#[inline(never)] pub fn g37(a: i64, b: i64) -> i64 { { let t23 = ((a).wrapping_sub((((((NeoInteger::new((if ((((((((8i64) < (a)) as i64)).wrapping_sub(1i64)) | (((((((64i64) as i16) as i64)) < ((((5734015868621396277i64) as i8) as i64))) as i64)))) < (((((b) as i32).rotate_right(((-2457208969433618297i64) & 31) as u32)) as i64))) { (b) } else { (1038166534352921092i64) })) / NeoInteger::new(((b) | 1))).as_i64_saturating())) as i8) as i64))); 63i64 } }
#[inline(never)] pub fn g38(a: i64, b: i64) -> i64 { ((((gdiv(((((7608811009704016765i64) as u32).wrapping_shr((((b).wrapping_abs())) as u32) as i32) as i64), (((4132220246161033076i64) == (((((((a) == (3061249979811515173i64)) as i64)) as u64) as i64))) as i64))) as u32).wrapping_shr((((NeoInteger::new(b) / NeoInteger::new(((((gdivu((if (((NeoInteger::new((((a) as u64).wrapping_shr((a) as u32) as i64)) / NeoInteger::new(((b) | 1))).as_i64_saturating())) != 0 { -6612430900039269375i64 } else { 7i64 }), b)).min(-2912430567878860515i64))) | 1))).as_i64_saturating())) as u32) as i32) as i64) }
#[inline(never)] pub fn g39(a: i64, b: i64) -> i64 { (if ((((((((8i64) as u32) as u64 as i64)) as i32) as i64)) < (b)) { ((-6513990813580722113i64).wrapping_shr((({ let mut acc24 = ((((((((a) as u64) < (((((((9223372036854775807i64).wrapping_shl((a) as u32)) as u32).wrapping_shr(((-1562969742114476314i64).wrapping_mul(1494118602321490243i64)) as u32) as i32) as i64)) as u64)) as i64)) as u16) as u64 as i64)); let n26 = (((-57334473927573887i64) & 7)); let mut i25 = 0i64; while i25 < n26 { acc24 = (acc24).wrapping_add((a)); i25 = i25 + 1; } acc24 }).wrapping_shr((7918284659559154131i64) as u32)) as u32)) } else { (b) }) }
#[inline(never)] pub fn g40(a: i64, b: i64) -> i64 { 5087523476620073066i64 }
#[inline(never)] pub fn g41(a: i64, b: i64) -> i64 { ((((4611686018427387904i64) as u64) < (((((-4615349057962775162i64) < (((((-5954076038617649401i64).count_ones() as i64)).wrapping_shl((((((((if (b) != 0 { -5357599587216507811i64 } else { -1125086594924484404i64 })).rotate_left(((((2i64) | (2147483647i64))) & 63) as u32))) | (-6491682156753164468i64))).wrapping_sub(b)) as u32)).wrapping_shl((a) as u32))) as i64)) as u64)) as i64) }
#[inline(never)] pub fn g42(a: i64, b: i64) -> i64 { ((({ let arr: [i64; 4] = [(((((NeoInteger::new((!((a).wrapping_shr((-4600986515426856709i64) as u32)))) % NeoInteger::new((({ let ma: [i64; 4] = [3956791154285108854i64, (if ((4070025767725999794i64) < (8792682420405619714i64)) { (a) } else { (7021118329107073441i64) }), (b).wrapping_shl((0i64) as u32), a]; let mut ms = 0i64; let mut mi = 0usize; while mi < 4 { ms = ms.wrapping_add(ma[mi]); mi += 1; } ms }) | 1))).as_i64_saturating())).wrapping_add(-1i64)) | (-2949381401803618141i64)), a, b, 4611686018427387904i64]; arr[(((b) & 3) as usize)] }).wrapping_shl((b) as u32)).rotate_left(((b) & 63) as u32)) }
#[inline(never)] pub fn g43(a: i64, b: i64) -> i64 { (((gdivu(0i64, ((a) & (((((255i64) ^ (b))) ^ (((((a).wrapping_abs())).count_ones() as i64))))))) < (((NeoInteger::new(((((gdiv(((8i64) ^ (((!NeoInteger::new((((a) < (a)) as i64))).as_i64_saturating()))), 255i64)) as u64) < ((32i64) as u64)) as i64)) / NeoInteger::new(((7678924014700561294i64) | 1))).as_i64_saturating()))) as i64) }
#[inline(never)] pub fn g44(a: i64, b: i64) -> i64 { (!(2286493917024232423i64)) }
#[inline(never)] pub fn g45(a: i64, b: i64) -> i64 { a }
#[inline(never)] pub fn g46(a: i64, b: i64) -> i64 { (((((2i64).wrapping_sub(((((-2147483648i64) as u32).wrapping_shr((((NeoInteger::new((((((((((((-256i64) as u64) < ((-2061537447425787290i64) as u64)) as i64)) as u32).wrapping_shr((((a).count_ones() as i64)) as u32) as i32) as i64)) == (((((((2147483648i64) < (b)) as i64)) as u64) as i64))) as i64)) % NeoInteger::new((({ let t27 = (256i64); a }) | 1))).as_i64_saturating())) as u32) as i32) as i64))).wrapping_neg())).min(b)) }
#[inline(never)] pub fn g47(a: i64, b: i64) -> i64 { b }
pub fn eval_idx(idx: i64, a: i64, b: i64) -> i64 {
    match idx {
        0 => g0(a, b),
        1 => g1(a, b),
        2 => g2(a, b),
        3 => g3(a, b),
        4 => g4(a, b),
        5 => g5(a, b),
        6 => g6(a, b),
        7 => g7(a, b),
        8 => g8(a, b),
        9 => g9(a, b),
        10 => g10(a, b),
        11 => g11(a, b),
        12 => g12(a, b),
        13 => g13(a, b),
        14 => g14(a, b),
        15 => g15(a, b),
        16 => g16(a, b),
        17 => g17(a, b),
        18 => g18(a, b),
        19 => g19(a, b),
        20 => g20(a, b),
        21 => g21(a, b),
        22 => g22(a, b),
        23 => g23(a, b),
        24 => g24(a, b),
        25 => g25(a, b),
        26 => g26(a, b),
        27 => g27(a, b),
        28 => g28(a, b),
        29 => g29(a, b),
        30 => g30(a, b),
        31 => g31(a, b),
        32 => g32(a, b),
        33 => g33(a, b),
        34 => g34(a, b),
        35 => g35(a, b),
        36 => g36(a, b),
        37 => g37(a, b),
        38 => g38(a, b),
        39 => g39(a, b),
        40 => g40(a, b),
        41 => g41(a, b),
        42 => g42(a, b),
        43 => g43(a, b),
        44 => g44(a, b),
        45 => g45(a, b),
        46 => g46(a, b),
        47 => g47(a, b),
        _ => 0,
    }
}
